/*
 * MIT License
 *
 * Copyright (c) 2025 Andreas Igel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.javahelpers.simple.builders.processor.generators;

import javax.annotation.processing.Generated;
import org.javahelpers.simple.builders.processor.dtos.AnnotationDto;
import org.javahelpers.simple.builders.processor.dtos.BuilderDefinitionDto;
import org.javahelpers.simple.builders.processor.dtos.TypeName;
import org.javahelpers.simple.builders.processor.util.JavaLangMapper;
import org.javahelpers.simple.builders.processor.util.ProcessingContext;

/**
 * Enhancer that adds the @Generated annotation to generated builder classes.
 *
 * <p>This enhancer adds the standard {@code @Generated} annotation to indicate that the builder
 * class was generated by the simple-builders annotation processor.
 *
 * <h3>Generated Annotation Example:</h3>
 *
 * <pre>
 * @Generated("Generated by org.javahelpers.simple.builders.processor.BuilderProcessor")
 * public class BookDtoBuilder {
 *   // ... builder implementation
 * }
 *
 * @Generated("Generated by org.javahelpers.simple.builders.processor.BuilderProcessor")
 * public class PersonDtoBuilder {
 *   // ... builder implementation
 * }
 * </pre>
 *
 * <p>The annotation includes information about the processor class and version to help with
 * debugging and code generation tracking.
 *
 * <p>Priority: 120 (highest - annotations should be added before most other enhancements)
 */
public class GeneratedAnnotationEnhancer implements BuilderEnhancer {

  private static final int PRIORITY = 120;

  @Override
  public int getPriority() {
    return PRIORITY;
  }

  @Override
  public boolean appliesTo(
      BuilderDefinitionDto builderDto, TypeName dtoType, ProcessingContext context) {
    return context.getConfiguration().shouldUseGeneratedAnnotation();
  }

  @Override
  public void enhanceBuilder(BuilderDefinitionDto builderDto, ProcessingContext context) {
    AnnotationDto generatedAnnotation = createGeneratedAnnotation(context);
    builderDto.addClassAnnotation(generatedAnnotation);

    context.debug(
        "Added @Generated annotation to builder %s",
        builderDto.getBuilderTypeName().getClassName());
  }

  /**
   * Creates the @Generated annotation.
   *
   * @param context the processing context
   * @return the annotation DTO for @Generated
   */
  private AnnotationDto createGeneratedAnnotation(ProcessingContext context) {
    AnnotationDto annotation = new AnnotationDto();
    annotation.setAnnotationType(JavaLangMapper.map2TypeName(Generated.class));

    // Add value member with processor class name (using the original name)
    annotation.addMember(
        "value", "\"Generated by org.javahelpers.simple.builders.processor.BuilderProcessor\"");

    return annotation;
  }
}
