#!/usr/bin/env python3
"""
Generate Java class/record source files from library-class-catalog.json.

The JSON blueprint defines all classes for the performance-test module. This
script reads the JSON and produces one .java file per class entry under
performance-test/src/main/java/... following the package layout from the plan:

  org.javahelpers.simple.builders.performance_test.library.<package>.<ClassName>

Only the classes defined in the JSON's ``packages.<name>.classes`` arrays are
generated. The fixed infrastructure (LibraryEntity, the 5 enums, and the 5
intermediate classes) is NOT generated by this script — create those by hand.

Usage:
  python3 generate_classes.py                      # generate all classes
  python3 generate_classes.py --limit 5            # generate only the first 5 classes (test mode)
  python3 generate_classes.py --dry-run            # print what would be written, write nothing
  python3 generate_classes.py --json other.json    # use an alternate JSON file
  python3 generate_classes.py --out other/dir      # use an alternate output root
  python3 generate_classes.py --force              # overwrite existing .java files

JSON schema (expected by this script):
  {
    "topic": "...",                       # ignored
    "totalClasses": <int>,                # ignored (computed from packages)
    "packages": {
      "<subPackage>": {                   # subPackage -> Java sub-package name
        "intermediateClass": "<Name>",    # ignored if per-class "extends" is set
        "classes": [
          {
            "name": "<ClassName>",         # required, must be a valid Java identifier
            "kind": "class" | "record",   # required
            "extends": "<Name>" | null,   # superclass for classes; ignored for records
            "properties": [
              {
                "name": "<propName>",      # required, valid Java identifier
                "type": "<JavaType>",      # required, e.g. "String", "List<Foo>", "int[]"
                "default": "<value>",      # optional -> @Default("value")
                "ignore": true             # optional -> @IgnoreInBuilder on setter
              }
            ]
          }
        ]
      }
    }
  }

Project-specific assumptions (hardcoded — edit the constants below to reuse
this script for a different project):
  - BASE_PACKAGE: the generated classes live under
    org.javahelpers.simple.builders.performance_test.library.<subPackage>
  - COPYRIGHT_YEAR / COPYRIGHT_HOLDER: the MIT license header in every file
  - ANNOTATION_IMPORTS: uses org.javahelpers.simple.builders.core.annotations
    (@SimpleBuilder, @Default, @IgnoreInBuilder)
  - Records get `implements <Name>Builder.With` (simple-builders convention)
  - ENUM_PACKAGE: enum types are expected in <BASE_PACKAGE>.enums
  - STANDARD_IMPORTS: a closed list of 12 Java standard types. Any property
    type that is NOT a primitive, NOT in STANDARD_IMPORTS, and NOT a class
    declared in the JSON is assumed to be an enum and imported from
    ENUM_PACKAGE. If you use a Java type not in STANDARD_IMPORTS (e.g.
    `Instant`, `ZonedDateTime`, `Collection`), add it to STANDARD_IMPORTS or
    it will be misclassified as an enum.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Iterable

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_JSON = SCRIPT_DIR.parent / "docs" / "library-class-catalog.json"
DEFAULT_OUT_ROOT = SCRIPT_DIR.parent / "src" / "main" / "java"

BASE_PACKAGE = "org.javahelpers.simple.builders.performance_test.library"
COPYRIGHT_YEAR = 2026
COPYRIGHT_HOLDER = "Andreas Igel"

# Java standard/3rd-party types that need imports, mapped to their fully
# qualified names. Only the simple name appears in the JSON.
STANDARD_IMPORTS: dict[str, str] = {
    "LocalDate": "java.time.LocalDate",
    "LocalTime": "java.time.LocalTime",
    "LocalDateTime": "java.time.LocalDateTime",
    "Duration": "java.time.Duration",
    "BigDecimal": "java.math.BigDecimal",
    "BigInteger": "java.math.BigInteger",
    "UUID": "java.util.UUID",
    "List": "java.util.List",
    "Set": "java.util.Set",
    "Map": "java.util.Map",
    "Optional": "java.util.Optional",
    "Date": "java.util.Date",
}

# Package where hand-written enum types live (fixed by the plan). Enum names
# themselves are NOT hardcoded — any property type that is neither a primitive,
# a standard Java type, nor a class declared in the JSON is assumed to be an
# enum imported from this package. This keeps the script JSON-driven: adding a
# new enum to the catalog only requires using it as a property type.
ENUM_PACKAGE = f"{BASE_PACKAGE}.enums"

# Annotation imports
ANNOTATION_IMPORTS: dict[str, str] = {
    "SimpleBuilder": "org.javahelpers.simple.builders.core.annotations.SimpleBuilder",
    "Default": "org.javahelpers.simple.builders.core.annotations.Default",
    "IgnoreInBuilder": "org.javahelpers.simple.builders.core.annotations.IgnoreInBuilder",
}

# Primitive types (no import needed, no wrapper logic for getters).
PRIMITIVES = {"int", "long", "double", "float", "boolean", "char", "byte", "short"}

# Valid ``kind`` values in the JSON.
VALID_KINDS = {"class", "record"}

# Regex for valid Java identifiers (JLS §3.8). Covers the ASCII subset, which
# is all we expect in this catalog. Keywords are technically valid identifiers
# but would produce non-compiling Java — we reject them separately below.
_JAVA_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

# Java keywords that must not be used as identifiers (JLS §3.9).
JAVA_KEYWORDS = {
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char",
    "class", "const", "continue", "default", "do", "double", "else", "enum",
    "extends", "final", "finally", "float", "for", "goto", "if", "implements",
    "import", "instanceof", "int", "interface", "long", "native", "new",
    "package", "private", "protected", "public", "return", "short", "static",
    "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while", "true", "false", "null",
    "record", "sealed", "permits", "var", "yield",
}


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------


class ValidationError(ValueError):
    """Raised when a JSON entry fails validation."""


def validate_identifier(name: str, label: str) -> None:
    """
    Validate that ``name`` is a safe Java identifier.

    This serves two purposes:
      1. Prevents path traversal — a name like ``../../etc/passwd`` would be
         used directly in a file path without this check.
      2. Ensures the generated Java compiles — ``int`` or ``123abc`` would not.

    Raises ``ValidationError`` if the name is not a valid Java identifier or
    is a Java keyword.
    """
    if not name:
        raise ValidationError(f"{label} is empty")
    if not _JAVA_IDENTIFIER_RE.match(name):
        raise ValidationError(
            f"{label} {name!r} is not a valid Java identifier "
            f"(contains illegal characters or starts with a digit)"
        )
    if name in JAVA_KEYWORDS:
        raise ValidationError(f"{label} {name!r} is a Java keyword and cannot be used as an identifier")


def validate_type_string(type_str: str, label: str) -> None:
    """
    Validate that ``type_str`` is a plausible Java type expression.

    This is a lightweight check — it rejects characters that have no business
    in a type expression (path separators, semicolons, etc.) and ensures every
    token within it is a valid Java identifier. It does NOT fully parse Java
    generics syntax.
    """
    if not type_str:
        raise ValidationError(f"{label} type is empty")
    # Reject characters that could be used for path traversal or injection.
    forbidden = {";", "/", "\\", ".."}
    for ch in forbidden:
        if ch in type_str:
            raise ValidationError(f"{label} type {type_str!r} contains forbidden character {ch!r}")
    # Every token must be a valid identifier (after stripping < > , [ ] spaces).
    for token in extract_simple_types(type_str):
        if token not in PRIMITIVES and token not in JAVA_KEYWORDS:
            if not _JAVA_IDENTIFIER_RE.match(token):
                raise ValidationError(
                    f"{label} type {type_str!r} contains invalid token {token!r}"
                )


def escape_java_string_literal(value: str) -> str:
    """
    Escape a string so it can be safely embedded inside a Java double-quoted
    string literal (e.g. for ``@Default("...")``).

    Escapes backslash, double quote, and common control characters.
    """
    result = []
    for ch in value:
        if ch == "\\":
            result.append("\\\\")
        elif ch == '"':
            result.append('\\"')
        elif ch == "\n":
            result.append("\\n")
        elif ch == "\r":
            result.append("\\r")
        elif ch == "\t":
            result.append("\\t")
        else:
            result.append(ch)
    return "".join(result)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def license_header() -> str:
    """Return the MIT license header used across the project."""
    return f"""/*
 * MIT License
 *
 * Copyright (c) {COPYRIGHT_YEAR} {COPYRIGHT_HOLDER}
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */"""


def capitalize(name: str) -> str:
    """Capitalize the first letter of ``name``."""
    return name[0].upper() + name[1:] if name else name


def extract_simple_types(type_str: str) -> set[str]:
    """
    Extract all simple type names referenced in a Java type string.

    Examples:
      "String"                  -> {"String"}
      "List<String>"            -> {"List", "String"}
      "Map<String,OtherDto>"    -> {"Map", "String", "OtherDto"}
      "Optional<List<Author>>"  -> {"Optional", "List", "Author"}
      "int[]"                   -> {"int"}
    """
    # Strip array brackets
    cleaned = type_str.replace("[]", "")
    # Split on anything that is not a Java identifier character
    tokens = re.split(r"[<>,\s]+", cleaned)
    return {t for t in tokens if t and t not in {"?", "extends", "super", "var"}}


def getter_name(field_name: str, field_type: str) -> str:
    """Return the getter method name following the JavaBeans convention."""
    cap = capitalize(field_name)
    return f"is{cap}" if field_type == "boolean" else f"get{cap}"


def setter_name(field_name: str) -> str:
    """Return the setter method name following the JavaBeans convention."""
    return f"set{capitalize(field_name)}"


def collect_class_index(data: dict) -> dict[str, str]:
    """
    Build a mapping ``class_name -> sub_package`` for every class defined in
    the JSON. Used to resolve cross-package imports for reference types.

    Raises ``ValidationError`` if duplicate class names are found.
    """
    index: dict[str, str] = {}
    for pkg_name, pkg in data.get("packages", {}).items():
        for cls in pkg.get("classes", []):
            name = cls.get("name")
            if not name:
                continue
            if name in index:
                raise ValidationError(
                    f"duplicate class name {name!r} found in package {pkg_name!r} "
                    f"(already defined in package {index[name]!r})"
                )
            index[name] = pkg_name
    return index


def resolve_imports(
    class_entry: dict,
    sub_package: str,
    class_index: dict[str, str],
) -> list[str]:
    """
    Determine the sorted list of import statements needed for a class/record.

    Rules:
      - Standard Java types (List, LocalDate, ...) -> java.* imports
      - Classes found in the JSON -> cross-package import, but only when the
        referenced class lives in a different sub-package (same-package types
        need no import).
      - Any other non-primitive, non-String type -> assumed to be an enum in
        .library.enums and imported from there. This avoids hardcoding enum
        names; the trade-off is that a genuinely unknown reference would also
        produce an (incorrect) enum import.
      - Primitives and String -> no import
    """
    needed: set[str] = set()
    uses_default = False
    uses_ignore = False

    for prop in class_entry.get("properties", []):
        prop_type = prop.get("type", "")
        for simple in extract_simple_types(prop_type):
            if simple in PRIMITIVES or simple == "String":
                continue
            if simple in STANDARD_IMPORTS:
                needed.add(STANDARD_IMPORTS[simple])
            elif simple in class_index:
                if class_index[simple] != sub_package:
                    ref_pkg = class_index[simple]
                    needed.add(f"{BASE_PACKAGE}.{ref_pkg}.{simple}")
                # same sub-package: no import needed
            else:
                # Not a primitive, not a standard Java type, not a JSON class:
                # assume it is an enum in the .library.enums package.
                needed.add(f"{ENUM_PACKAGE}.{simple}")
        if "default" in prop:
            uses_default = True
        if prop.get("ignore"):
            uses_ignore = True

    # @SimpleBuilder is always used
    needed.add(ANNOTATION_IMPORTS["SimpleBuilder"])
    if uses_default:
        needed.add(ANNOTATION_IMPORTS["Default"])
    if uses_ignore:
        needed.add(ANNOTATION_IMPORTS["IgnoreInBuilder"])

    return sorted(needed)


# ---------------------------------------------------------------------------
# Source generation
# ---------------------------------------------------------------------------


def generate_class_source(
    class_entry: dict,
    intermediate_class: str,
    sub_package: str,
    class_index: dict[str, str],
) -> str:
    """
    Generate the full Java source for a ``kind: "class"`` entry.

    The ``extends`` clause uses the per-class ``extends`` field from the JSON.
    If it is null or absent, the class has no superclass. If it is set, that
    value is used (typically the package's intermediate class).
    """
    name = class_entry["name"]
    props = class_entry.get("properties", [])
    imports = resolve_imports(class_entry, sub_package, class_index)
    package_decl = f"{BASE_PACKAGE}.{sub_package}"

    # Determine extends clause from the per-class field.
    extends_value = class_entry.get("extends")
    extends_clause = f" extends {extends_value}" if extends_value else ""

    lines: list[str] = []
    lines.append(license_header())
    lines.append("")
    lines.append(f"package {package_decl};")
    lines.append("")
    if imports:
        for imp in imports:
            lines.append(f"import {imp};")
        lines.append("")
    lines.append("@SimpleBuilder")
    lines.append(f"public class {name}{extends_clause} {{")
    lines.append("")

    # Fields
    for prop in props:
        field_name = prop["name"]
        field_type = prop["type"]
        annotations: list[str] = []
        if "default" in prop:
            escaped = escape_java_string_literal(str(prop["default"]))
            annotations.append(f'@Default("{escaped}")')
        # NOTE: @IgnoreInBuilder targets METHOD/PARAMETER, not FIELD, so it is
        # placed on the setter below, not here.
        indent = "  "
        for ann in annotations:
            lines.append(f"{indent}{ann}")
        lines.append(f"{indent}private {field_type} {field_name};")
    lines.append("")

    # Getters and setters
    for prop in props:
        field_name = prop["name"]
        field_type = prop["type"]
        getter = getter_name(field_name, field_type)
        setter = setter_name(field_name)
        indent = "  "

        # Getter
        lines.append(f"{indent}public {field_type} {getter}() {{")
        lines.append(f"{indent}  return {field_name};")
        lines.append(f"{indent}}}")
        lines.append("")

        # Setter (with @IgnoreInBuilder if flagged)
        if prop.get("ignore"):
            lines.append(f"{indent}@IgnoreInBuilder")
        lines.append(f"{indent}public void {setter}({field_type} {field_name}) {{")
        lines.append(f"{indent}  this.{field_name} = {field_name};")
        lines.append(f"{indent}}}")
        lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_record_source(
    class_entry: dict,
    sub_package: str,
    class_index: dict[str, str],
) -> str:
    """Generate the full Java source for a ``kind: "record"`` entry."""
    name = class_entry["name"]
    props = class_entry.get("properties", [])
    imports = resolve_imports(class_entry, sub_package, class_index)
    package_decl = f"{BASE_PACKAGE}.{sub_package}"

    lines: list[str] = []
    lines.append(license_header())
    lines.append("")
    lines.append(f"package {package_decl};")
    lines.append("")
    if imports:
        for imp in imports:
            lines.append(f"import {imp};")
        lines.append("")
    lines.append("@SimpleBuilder")
    lines.append(f"public record {name}(")

    # Record components
    for i, prop in enumerate(props):
        field_name = prop["name"]
        field_type = prop["type"]
        annotations: list[str] = []
        if "default" in prop:
            escaped = escape_java_string_literal(str(prop["default"]))
            annotations.append(f'@Default("{escaped}")')
        if prop.get("ignore"):
            annotations.append("@IgnoreInBuilder")
        prefix = "    "
        if annotations:
            ann_str = "\n".join(f"{prefix}{a}" for a in annotations) + "\n" + prefix
        else:
            ann_str = prefix
        comma = "," if i < len(props) - 1 else ""
        lines.append(f"{ann_str}{field_type} {field_name}{comma}")

    lines.append(f") implements {name}Builder.With {{")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_source(
    class_entry: dict,
    intermediate_class: str,
    sub_package: str,
    class_index: dict[str, str],
) -> str:
    """Dispatch to the correct generator based on ``kind``."""
    kind = class_entry.get("kind", "class")
    if kind == "record":
        return generate_record_source(class_entry, sub_package, class_index)
    return generate_class_source(class_entry, intermediate_class, sub_package, class_index)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def iter_classes(data: dict) -> Iterable[tuple[str, str, dict]]:
    """
    Yield ``(sub_package, intermediate_class, class_entry)`` tuples in JSON
    order: items, persons, organizations, locations, events, and within each
    package the classes in array order.
    """
    for pkg_name, pkg in data.get("packages", {}).items():
        intermediate = pkg.get("intermediateClass", "")
        for cls in pkg.get("classes", []):
            yield pkg_name, intermediate, cls


def atomic_write(path: Path, content: str) -> None:
    """
    Write ``content`` to ``path`` atomically.

    Writes to a temporary file in the same directory, then renames it to the
    target. This ensures that if the process is interrupted, the target file
    is either the old version or the complete new version — never a partial
    write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    # Use the same directory as the target so the rename is atomic on the same
    # filesystem. NamedTemporaryFile handles the unique-name and cleanup-on-
    # error logic.
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.stem}.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(content)
        tmp.flush()
        os.fsync(tmp.fileno())
        tmp_path = Path(tmp.name)
    # os.replace is atomic on POSIX and Windows (Python 3.3+).
    os.replace(tmp_path, path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Java class files from library-class-catalog.json.",
    )
    parser.add_argument(
        "--json",
        type=Path,
        default=DEFAULT_JSON,
        help=f"Path to the catalog JSON (default: {DEFAULT_JSON})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT_ROOT,
        help=f"Output root directory (default: {DEFAULT_OUT_ROOT})",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Only generate the first N classes (test mode, e.g. --limit 5).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the paths that would be written without writing any files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing .java files (default: skip them).",
    )
    args = parser.parse_args(argv)

    json_path: Path = args.json
    out_root: Path = args.out
    limit: int | None = args.limit

    if limit is not None and limit < 0:
        print("error: --limit must be >= 0", file=sys.stderr)
        return 2

    if not json_path.is_file():
        print(f"error: JSON file not found: {json_path}", file=sys.stderr)
        return 2

    try:
        with json_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"error: invalid JSON in {json_path}: {e}", file=sys.stderr)
        return 2

    # Build class index and validate uniqueness.
    try:
        class_index = collect_class_index(data)
    except ValidationError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    total_in_json = sum(len(p.get("classes", [])) for p in data.get("packages", {}).values())
    n_to_generate = min(limit, total_in_json) if limit is not None else total_in_json

    print(f"JSON:       {json_path}")
    print(f"Output:     {out_root}")
    print(f"Classes in JSON: {total_in_json}")
    if limit is not None:
        print(f"Limit:      first {n_to_generate} class(es) (test mode)")
    print()

    written = 0
    skipped = 0
    errors: list[str] = []

    for idx, (sub_package, intermediate, cls) in enumerate(iter_classes(data)):
        if limit is not None and idx >= limit:
            break

        # --- Validate the entry before generating anything ---
        try:
            name = cls.get("name")
            if not name:
                raise ValidationError(f"class entry at index {idx} has no name")
            validate_identifier(name, f"class name (index {idx})")
            validate_identifier(sub_package, f"package name (index {idx})")

            kind = cls.get("kind", "class")
            if kind not in VALID_KINDS:
                raise ValidationError(
                    f"class {name!r} has invalid kind {kind!r}; "
                    f"expected one of {sorted(VALID_KINDS)}"
                )

            # Validate extends if present.
            extends_value = cls.get("extends")
            if extends_value is not None:
                validate_identifier(str(extends_value), f"extends in class {name!r}")

            # Validate each property.
            for prop in cls.get("properties", []):
                prop_name = prop.get("name")
                if not prop_name:
                    raise ValidationError(f"class {name!r} has a property without a name")
                validate_identifier(prop_name, f"property name in class {name!r}")
                prop_type = prop.get("type")
                if prop_type is None:
                    raise ValidationError(
                        f"property {prop_name!r} in class {name!r} has no type"
                    )
                validate_type_string(str(prop_type), f"property {prop_name!r} in class {name!r}")

        except ValidationError as e:
            errors.append(str(e))
            print(f"  ERROR: {e}", file=sys.stderr)
            continue

        # --- Generate source ---
        try:
            source = generate_source(cls, intermediate, sub_package, class_index)
        except (KeyError, TypeError) as e:
            msg = f"failed to generate source for class {name!r}: {e}"
            errors.append(msg)
            print(f"  ERROR: {msg}", file=sys.stderr)
            continue

        rel_path = Path(*BASE_PACKAGE.split(".")) / sub_package / f"{name}.java"
        out_file = out_root / rel_path

        # Safety: ensure the resolved path is still under out_root (defense in
        # depth, even though identifiers are validated above).
        try:
            out_file.resolve().relative_to(out_root.resolve())
        except ValueError:
            msg = f"refusing to write outside output root: {out_file}"
            errors.append(msg)
            print(f"  ERROR: {msg}", file=sys.stderr)
            continue

        if args.dry_run:
            print(f"  [dry-run] {out_file}  ({len(source)} bytes)")
            continue

        if out_file.exists() and not args.force:
            print(f"  skip (exists): {out_file}")
            skipped += 1
            continue

        try:
            atomic_write(out_file, source)
        except OSError as e:
            msg = f"failed to write {out_file}: {e}"
            errors.append(msg)
            print(f"  ERROR: {msg}", file=sys.stderr)
            continue

        print(f"  wrote: {out_file}")
        written += 1

    print()
    if args.dry_run:
        print(f"Dry run complete — {n_to_generate} class(es) would be generated.")
    else:
        print(f"Done — wrote {written} file(s), skipped {skipped} existing file(s).")
    if errors:
        print(f"\n{len(errors)} error(s) occurred:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
