package org.javahelpers.simple.builders.example;

import static org.javahelpers.simple.builders.core.util.TrackedValue.changedValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.initialValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.unsetValue;
import java.util.function.BooleanSupplier;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import javax.annotation.processing.Generated;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.javahelpers.simple.builders.core.annotations.BuilderImplementation;
import org.javahelpers.simple.builders.core.interfaces.IBuilderBase;
import org.javahelpers.simple.builders.core.util.BuilderToStringStyle;
import org.javahelpers.simple.builders.core.util.TrackedValue;
import org.javahelpers.simple.builders.example.external.ExternalAddress;

/**
 * Builder for {@code org.javahelpers.simple.builders.example.external.ExternalAddress}.
 * <p>
 * This builder provides a fluent API for creating instances of
 * org.javahelpers.simple.builders.example.external.ExternalAddress with method chaining and validation. Use the static
 * {@code create()} method to obtain a new builder instance, configure the desired properties using the setter methods,
 * and then call {@code build()} to create the final DTO.
 * 
 * <h4>Example:</h4>
 * 
 * <pre>{@code
 * ExternalAddress result = ExternalAddressBuilder.create()
 *     .city("example value")
 *     .city("Hello %s", "World")
 *     .city(() -> "example value")
 *     .city(sb -> sb.append("text"))
 *     .cityUpdate(String::trim)
 *     .street("example value")
 *     .street("Hello %s", "World")
 *     .street(() -> "example value")
 *     .street(sb -> sb.append("text"))
 *     .streetUpdate(String::trim)
 *     .zipCode("example value")
 *     .zipCode("Hello %s", "World")
 *     .zipCode(() -> "example value")
 *     .zipCode(sb -> sb.append("text"))
 *     .zipCodeUpdate(String::trim)
 *     .build();
 * }</pre>
 */
@Generated("Generated by org.javahelpers.simple.builders.processor.BuilderProcessor")
@BuilderImplementation(forClass = ExternalAddress.class)
public class ExternalAddressBuilder implements IBuilderBase<ExternalAddress> {

  /**
   * Tracked value for <code>city</code>: city.
   */
  private TrackedValue<String> city = unsetValue();
  /**
   * Tracked value for <code>street</code>: street.
   */
  private TrackedValue<String> street = unsetValue();
  /**
   * Tracked value for <code>zipCode</code>: zipCode.
   */
  private TrackedValue<String> zipCode = unsetValue();

  /**
   * Empty constructor of builder for {@code org.javahelpers.simple.builders.example.external.ExternalAddress}.
   */
  public ExternalAddressBuilder() {
  }

  /**
   * Initialisation of builder for {@code org.javahelpers.simple.builders.example.external.ExternalAddress} by a
   * instance.
   * 
   * @param instance object instance for initialisiation
   */
  public ExternalAddressBuilder(ExternalAddress instance) {
    this.city = initialValue(instance.getCity());
    this.street = initialValue(instance.getStreet());
    this.zipCode = initialValue(instance.getZipCode());
  }

  /**
   * Creating a new builder for {@code org.javahelpers.simple.builders.example.external.ExternalAddress}.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * ExternalAddressBuilder builder = ExternalAddressBuilder.create();
   * }</pre>
   * 
   * @return builder for {@code org.javahelpers.simple.builders.example.external.ExternalAddress}
   */
  public static ExternalAddressBuilder create() {
    return new ExternalAddressBuilder();
  }

  /**
   * Sets the value for <code>city</code>.
   * <p>
   * Generated from setter {@link ExternalAddress#setCity(String) setCity(String city)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.city("example value");
   * }</pre>
   * 
   * @param city city
   * @return current instance of builder
   */
  public ExternalAddressBuilder city(String city) {
    this.city = changedValue(city);
    return this;
  }

  /**
   * Sets the value for <code>city</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link ExternalAddress#setCity(String) setCity(String city)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.city(sb -> sb.append("text"));
   * }</pre>
   * 
   * @param cityStringBuilderConsumer consumer providing an instance of city
   * @return current instance of builder
   */
  public ExternalAddressBuilder city(Consumer<StringBuilder> cityStringBuilderConsumer) {
    StringBuilder builder = new StringBuilder();
    cityStringBuilderConsumer.accept(builder);
    this.city = changedValue(builder.toString());
    return this;
  }

  /**
   * Sets the value for <code>city</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link ExternalAddress#setCity(String) setCity(String city)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.city(() -> "example value");
   * }</pre>
   * 
   * @param citySupplier supplier for city
   * @return current instance of builder
   */
  public ExternalAddressBuilder city(Supplier<String> citySupplier) {
    this.city = changedValue(citySupplier.get());
    return this;
  }

  /**
   * Sets the String value for <code>city</code> by using String.format(format, args). See
   * {@link String#format(String, Object...)} for details.
   * <p>
   * Generated from setter {@link ExternalAddress#setCity(String) setCity(String city)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.city("Hello %s", "World");
   * }</pre>
   * 
   * @param format A format string
   * @param args Arguments referenced by the format specifiers in the format string.
   * @return current instance of builder
   */
  public ExternalAddressBuilder city(String format, Object... args) {
    this.city = changedValue(String.format(format, args));
    return this;
  }

  /**
   * Updates the current value of <code>city</code> in place by applying the given operator, instead of reading it out,
   * changing it and setting it again. Useful for adjustments relative to the current value, e.g. trimming,
   * upper-casing, clamping or incrementing, and in combination with the <code>With</code> copy-and-modify flow. The
   * value must have been set before (directly or via an existing instance).
   * <p>
   * Generated from setter {@link ExternalAddress#setCity(String) setCity(String city)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.city("example value").cityUpdate(String::trim);
   * }</pre>
   * 
   * @param cityUpdater operator applied to the current value; its result becomes the new value
   * @return current instance of builder
   * @throws IllegalStateException if <code>city</code> has not been set yet
   */
  public ExternalAddressBuilder cityUpdate(UnaryOperator<String> cityUpdater) {
    if (!this.city.isSet()) {
      throw new IllegalStateException("Cannot update 'city' before it is set");
    }
    this.city = changedValue(cityUpdater.apply(this.city.value()));
    return this;
  }

  /**
   * Sets the value for <code>street</code>.
   * <p>
   * Generated from setter {@link ExternalAddress#setStreet(String) setStreet(String street)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.street("example value");
   * }</pre>
   * 
   * @param street street
   * @return current instance of builder
   */
  public ExternalAddressBuilder street(String street) {
    this.street = changedValue(street);
    return this;
  }

  /**
   * Sets the value for <code>street</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link ExternalAddress#setStreet(String) setStreet(String street)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.street(sb -> sb.append("text"));
   * }</pre>
   * 
   * @param streetStringBuilderConsumer consumer providing an instance of street
   * @return current instance of builder
   */
  public ExternalAddressBuilder street(Consumer<StringBuilder> streetStringBuilderConsumer) {
    StringBuilder builder = new StringBuilder();
    streetStringBuilderConsumer.accept(builder);
    this.street = changedValue(builder.toString());
    return this;
  }

  /**
   * Sets the value for <code>street</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link ExternalAddress#setStreet(String) setStreet(String street)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.street(() -> "example value");
   * }</pre>
   * 
   * @param streetSupplier supplier for street
   * @return current instance of builder
   */
  public ExternalAddressBuilder street(Supplier<String> streetSupplier) {
    this.street = changedValue(streetSupplier.get());
    return this;
  }

  /**
   * Sets the String value for <code>street</code> by using String.format(format, args). See
   * {@link String#format(String, Object...)} for details.
   * <p>
   * Generated from setter {@link ExternalAddress#setStreet(String) setStreet(String street)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.street("Hello %s", "World");
   * }</pre>
   * 
   * @param format A format string
   * @param args Arguments referenced by the format specifiers in the format string.
   * @return current instance of builder
   */
  public ExternalAddressBuilder street(String format, Object... args) {
    this.street = changedValue(String.format(format, args));
    return this;
  }

  /**
   * Updates the current value of <code>street</code> in place by applying the given operator, instead of reading it
   * out, changing it and setting it again. Useful for adjustments relative to the current value, e.g. trimming,
   * upper-casing, clamping or incrementing, and in combination with the <code>With</code> copy-and-modify flow. The
   * value must have been set before (directly or via an existing instance).
   * <p>
   * Generated from setter {@link ExternalAddress#setStreet(String) setStreet(String street)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.street("example value").streetUpdate(String::trim);
   * }</pre>
   * 
   * @param streetUpdater operator applied to the current value; its result becomes the new value
   * @return current instance of builder
   * @throws IllegalStateException if <code>street</code> has not been set yet
   */
  public ExternalAddressBuilder streetUpdate(UnaryOperator<String> streetUpdater) {
    if (!this.street.isSet()) {
      throw new IllegalStateException("Cannot update 'street' before it is set");
    }
    this.street = changedValue(streetUpdater.apply(this.street.value()));
    return this;
  }

  /**
   * Validates that the city field is not null or empty.
   * <p>
   * Generated from setter {@link ExternalAddress#setCity(String) setCity(String city)}
   * 
   * @return this builder instance for chaining
   * @throws IllegalArgumentException if city is null or empty
   */
  ExternalAddressBuilder validateCity() {
    if (!city.isSet() || city.value().trim().isEmpty()) {
      throw new IllegalArgumentException("City cannot be null or empty");
    }
    return this;
  }

  /**
   * Validates that the street field is not null or empty.
   * <p>
   * Generated from setter {@link ExternalAddress#setStreet(String) setStreet(String street)}
   * 
   * @return this builder instance for chaining
   * @throws IllegalArgumentException if street is null or empty
   */
  ExternalAddressBuilder validateStreet() {
    if (!street.isSet() || street.value().trim().isEmpty()) {
      throw new IllegalArgumentException("Street cannot be null or empty");
    }
    return this;
  }

  /**
   * Validates that the zipCode field is not null or empty.
   * <p>
   * Generated from setter {@link ExternalAddress#setZipCode(String) setZipCode(String zipCode)}
   * 
   * @return this builder instance for chaining
   * @throws IllegalArgumentException if zipCode is null or empty
   */
  ExternalAddressBuilder validateZipCode() {
    if (!zipCode.isSet() || zipCode.value().trim().isEmpty()) {
      throw new IllegalArgumentException("ZipCode cannot be null or empty");
    }
    return this;
  }

  /**
   * Sets the value for <code>zipCode</code>.
   * <p>
   * Generated from setter {@link ExternalAddress#setZipCode(String) setZipCode(String zipCode)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.zipCode("example value");
   * }</pre>
   * 
   * @param zipCode zipCode
   * @return current instance of builder
   */
  public ExternalAddressBuilder zipCode(String zipCode) {
    this.zipCode = changedValue(zipCode);
    return this;
  }

  /**
   * Sets the value for <code>zipCode</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link ExternalAddress#setZipCode(String) setZipCode(String zipCode)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.zipCode(sb -> sb.append("text"));
   * }</pre>
   * 
   * @param zipCodeStringBuilderConsumer consumer providing an instance of zipCode
   * @return current instance of builder
   */
  public ExternalAddressBuilder zipCode(Consumer<StringBuilder> zipCodeStringBuilderConsumer) {
    StringBuilder builder = new StringBuilder();
    zipCodeStringBuilderConsumer.accept(builder);
    this.zipCode = changedValue(builder.toString());
    return this;
  }

  /**
   * Sets the value for <code>zipCode</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link ExternalAddress#setZipCode(String) setZipCode(String zipCode)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.zipCode(() -> "example value");
   * }</pre>
   * 
   * @param zipCodeSupplier supplier for zipCode
   * @return current instance of builder
   */
  public ExternalAddressBuilder zipCode(Supplier<String> zipCodeSupplier) {
    this.zipCode = changedValue(zipCodeSupplier.get());
    return this;
  }

  /**
   * Sets the String value for <code>zipCode</code> by using String.format(format, args). See
   * {@link String#format(String, Object...)} for details.
   * <p>
   * Generated from setter {@link ExternalAddress#setZipCode(String) setZipCode(String zipCode)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.zipCode("Hello %s", "World");
   * }</pre>
   * 
   * @param format A format string
   * @param args Arguments referenced by the format specifiers in the format string.
   * @return current instance of builder
   */
  public ExternalAddressBuilder zipCode(String format, Object... args) {
    this.zipCode = changedValue(String.format(format, args));
    return this;
  }

  /**
   * Updates the current value of <code>zipCode</code> in place by applying the given operator, instead of reading it
   * out, changing it and setting it again. Useful for adjustments relative to the current value, e.g. trimming,
   * upper-casing, clamping or incrementing, and in combination with the <code>With</code> copy-and-modify flow. The
   * value must have been set before (directly or via an existing instance).
   * <p>
   * Generated from setter {@link ExternalAddress#setZipCode(String) setZipCode(String zipCode)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.zipCode("example value").zipCodeUpdate(String::trim);
   * }</pre>
   * 
   * @param zipCodeUpdater operator applied to the current value; its result becomes the new value
   * @return current instance of builder
   * @throws IllegalStateException if <code>zipCode</code> has not been set yet
   */
  public ExternalAddressBuilder zipCodeUpdate(UnaryOperator<String> zipCodeUpdater) {
    if (!this.zipCode.isSet()) {
      throw new IllegalStateException("Cannot update 'zipCode' before it is set");
    }
    this.zipCode = changedValue(zipCodeUpdater.apply(this.zipCode.value()));
    return this;
  }

  /**
   * Conditionally applies builder modifications if the condition is true.
   * 
   * @param condition the condition to evaluate
   * @param yesCondition the consumer to apply if condition is true
   * @return this builder instance
   */
  public ExternalAddressBuilder conditional(BooleanSupplier condition, Consumer<ExternalAddressBuilder> yesCondition) {
    return conditional(condition, yesCondition, null);
  }

  /**
   * Conditionally applies builder modifications based on a condition evaluation.
   * 
   * @param condition the condition to evaluate
   * @param trueCase the consumer to apply if condition is true
   * @param falseCase the consumer to apply if condition is false (can be null)
   * @return this builder instance
   */
  public ExternalAddressBuilder conditional(BooleanSupplier condition, Consumer<ExternalAddressBuilder> trueCase,
      Consumer<ExternalAddressBuilder> falseCase) {
    if (condition.getAsBoolean()) {
      trueCase.accept(this);
    } else if (falseCase != null) {
      falseCase.accept(this);
    }
    return this;
  }

  /**
   * Builds the configured DTO instance.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * ExternalAddress result = builder.build();
   * }</pre>
   */
  @Override
  public ExternalAddress build() {
    ExternalAddress result = new ExternalAddress();
    this.city.ifSet(result::setCity);
    this.street.ifSet(result::setStreet);
    this.zipCode.ifSet(result::setZipCode);
    return result;
  }

  /**
   * Returns a string representation of this builder, including only fields that have been set.
   * 
   * @return string representation of the builder
   */
  @Override
  public String toString() {
    return new ToStringBuilder(this, BuilderToStringStyle.INSTANCE).append("city", this.city)
        .append("street", this.street)
        .append("zipCode", this.zipCode)
        .toString();
  }

  /**
   * Interface that can be implemented by the DTO to provide fluent modification methods.
   */
  public interface With {
    /**
     * Initializes a builder from an instance of this class, using methods of this builder to change values and returns
     * the new built object.
     * 
     * @param b the consumer to apply modifications
     * @return the modified instance
     */
    default ExternalAddress with(Consumer<ExternalAddressBuilder> b) {
      ExternalAddressBuilder builder;
      try {
        builder = new ExternalAddressBuilder(ExternalAddress.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'ExternalAddressBuilder.With' should only be implemented by classes, which could be casted to 'ExternalAddress'",
            ex);
      }
      b.accept(builder);
      return builder.build();
    }

    /**
     * Creates a builder initialized from this instance.
     * 
     * @return a builder initialized with this instance's values
     */
    default ExternalAddressBuilder with() {
      try {
        return new ExternalAddressBuilder(ExternalAddress.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'ExternalAddressBuilder.With' should only be implemented by classes, which could be casted to 'ExternalAddress'",
            ex);
      }
    }
  }
}