package org.javahelpers.simple.builders.example;

import static org.javahelpers.simple.builders.core.util.TrackedValue.changedValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.initialValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.unsetValue;
import java.util.function.BooleanSupplier;
import java.util.function.Consumer;
import java.util.function.Supplier;
import javax.annotation.processing.Generated;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.javahelpers.simple.builders.core.annotations.BuilderImplementation;
import org.javahelpers.simple.builders.core.interfaces.IBuilderBase;
import org.javahelpers.simple.builders.core.util.BuilderToStringStyle;
import org.javahelpers.simple.builders.core.util.TrackedValue;

/**
 * Builder for {@code org.javahelpers.simple.builders.example.OrderWithDefaults}.
 * <p>
 * This builder provides a fluent API for creating instances of
 * org.javahelpers.simple.builders.example.OrderWithDefaults with method chaining and validation. Use the static
 * {@code create()} method to obtain a new builder instance, configure the desired properties using the setter methods,
 * and then call {@code build()} to create the final DTO.
 * 
 * <h4>Example:</h4>
 * 
 * <pre>{@code
 * OrderWithDefaults result = OrderWithDefaultsBuilder.create()
 *     .id("example value")
 *     .id("Hello %s", "World")
 *     .id(() -> "example value")
 *     .id(sb -> sb.append("text"))
 *     .priority(42)
 *     .priority(() -> 42)
 *     .status("example value")
 *     .status("Hello %s", "World")
 *     .status(() -> "example value")
 *     .status(sb -> sb.append("text"))
 *     .build();
 * }</pre>
 */
@Generated("Generated by org.javahelpers.simple.builders.processor.BuilderProcessor")
@BuilderImplementation(forClass = OrderWithDefaults.class)
public class OrderWithDefaultsBuilder implements IBuilderBase<OrderWithDefaults> {

  /**
   * Tracked value for <code>id</code>: id.
   */
  private TrackedValue<String> id = unsetValue();
  /**
   * Tracked value for <code>priority</code>: priority.
   */
  private TrackedValue<Integer> priority = unsetValue();
  /**
   * Tracked value for <code>status</code>: status.
   */
  private TrackedValue<String> status = unsetValue();

  /**
   * Empty constructor of builder for {@code org.javahelpers.simple.builders.example.OrderWithDefaults}.
   */
  public OrderWithDefaultsBuilder() {
  }

  /**
   * Initialisation of builder for {@code org.javahelpers.simple.builders.example.OrderWithDefaults} by a instance.
   * 
   * @param instance object instance for initialisiation
   */
  public OrderWithDefaultsBuilder(OrderWithDefaults instance) {
    this.id = initialValue(instance.getId());
    this.priority = initialValue(instance.getPriority());
    this.status = initialValue(instance.getStatus());
  }

  /**
   * Creating a new builder for {@code org.javahelpers.simple.builders.example.OrderWithDefaults}.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * OrderWithDefaultsBuilder builder = OrderWithDefaultsBuilder.create();
   * }</pre>
   * 
   * @return builder for {@code org.javahelpers.simple.builders.example.OrderWithDefaults}
   */
  public static OrderWithDefaultsBuilder create() {
    return new OrderWithDefaultsBuilder();
  }

  /**
   * Sets the value for <code>id</code>.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setId(String) setId(String id)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.id("example value");
   * }</pre>
   * 
   * @param id id
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder id(String id) {
    this.id = changedValue(id);
    return this;
  }

  /**
   * Sets the value for <code>id</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setId(String) setId(String id)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.id(sb -> sb.append("text"));
   * }</pre>
   * 
   * @param idStringBuilderConsumer consumer providing an instance of id
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder id(Consumer<StringBuilder> idStringBuilderConsumer) {
    StringBuilder builder = new StringBuilder();
    idStringBuilderConsumer.accept(builder);
    this.id = changedValue(builder.toString());
    return this;
  }

  /**
   * Sets the value for <code>id</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setId(String) setId(String id)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.id(() -> "example value");
   * }</pre>
   * 
   * @param idSupplier supplier for id
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder id(Supplier<String> idSupplier) {
    this.id = changedValue(idSupplier.get());
    return this;
  }

  /**
   * Sets the String value for <code>id</code> by using String.format(format, args). See
   * {@link String#format(String, Object...)} for details.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setId(String) setId(String id)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.id("Hello %s", "World");
   * }</pre>
   * 
   * @param format A format string
   * @param args Arguments referenced by the format specifiers in the format string.
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder id(String format, Object... args) {
    this.id = changedValue(String.format(format, args));
    return this;
  }

  /**
   * Sets the value for <code>priority</code>.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setPriority(int) setPriority(int priority)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.priority(42);
   * }</pre>
   * 
   * @param priority priority
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder priority(int priority) {
    this.priority = changedValue(priority);
    return this;
  }

  /**
   * Sets the value for <code>priority</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setPriority(int) setPriority(int priority)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.priority(() -> 42);
   * }</pre>
   * 
   * @param prioritySupplier supplier for priority
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder priority(Supplier<Integer> prioritySupplier) {
    this.priority = changedValue(prioritySupplier.get());
    return this;
  }

  /**
   * Sets the value for <code>status</code>.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setStatus(String) setStatus(String status)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.status("example value");
   * }</pre>
   * 
   * @param status status
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder status(String status) {
    this.status = changedValue(status);
    return this;
  }

  /**
   * Sets the value for <code>status</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setStatus(String) setStatus(String status)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.status(sb -> sb.append("text"));
   * }</pre>
   * 
   * @param statusStringBuilderConsumer consumer providing an instance of status
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder status(Consumer<StringBuilder> statusStringBuilderConsumer) {
    StringBuilder builder = new StringBuilder();
    statusStringBuilderConsumer.accept(builder);
    this.status = changedValue(builder.toString());
    return this;
  }

  /**
   * Sets the value for <code>status</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setStatus(String) setStatus(String status)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.status(() -> "example value");
   * }</pre>
   * 
   * @param statusSupplier supplier for status
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder status(Supplier<String> statusSupplier) {
    this.status = changedValue(statusSupplier.get());
    return this;
  }

  /**
   * Sets the String value for <code>status</code> by using String.format(format, args). See
   * {@link String#format(String, Object...)} for details.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setStatus(String) setStatus(String status)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.status("Hello %s", "World");
   * }</pre>
   * 
   * @param format A format string
   * @param args Arguments referenced by the format specifiers in the format string.
   * @return current instance of builder
   */
  public OrderWithDefaultsBuilder status(String format, Object... args) {
    this.status = changedValue(String.format(format, args));
    return this;
  }

  /**
   * Validates that the id field is not null or empty.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setId(String) setId(String id)}
   * 
   * @return this builder instance for chaining
   * @throws IllegalArgumentException if id is null or empty
   */
  OrderWithDefaultsBuilder validateId() {
    if (!id.isSet() || id.value().trim().isEmpty()) {
      throw new IllegalArgumentException("Id cannot be null or empty");
    }
    return this;
  }

  /**
   * Validates that the status field is not null or empty.
   * <p>
   * Generated from setter {@link OrderWithDefaults#setStatus(String) setStatus(String status)}
   * 
   * @return this builder instance for chaining
   * @throws IllegalArgumentException if status is null or empty
   */
  OrderWithDefaultsBuilder validateStatus() {
    if (!status.isSet() || status.value().trim().isEmpty()) {
      throw new IllegalArgumentException("Status cannot be null or empty");
    }
    return this;
  }

  /**
   * Conditionally applies builder modifications if the condition is true.
   * 
   * @param condition the condition to evaluate
   * @param yesCondition the consumer to apply if condition is true
   * @return this builder instance
   */
  public OrderWithDefaultsBuilder conditional(BooleanSupplier condition,
      Consumer<OrderWithDefaultsBuilder> yesCondition) {
    return conditional(condition, yesCondition, null);
  }

  /**
   * Conditionally applies builder modifications based on a condition evaluation.
   * 
   * @param condition the condition to evaluate
   * @param trueCase the consumer to apply if condition is true
   * @param falseCase the consumer to apply if condition is false (can be null)
   * @return this builder instance
   */
  public OrderWithDefaultsBuilder conditional(BooleanSupplier condition, Consumer<OrderWithDefaultsBuilder> trueCase,
      Consumer<OrderWithDefaultsBuilder> falseCase) {
    if (condition.getAsBoolean()) {
      trueCase.accept(this);
    } else if (falseCase != null) {
      falseCase.accept(this);
    }
    return this;
  }

  /**
   * Builds the configured DTO instance.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * OrderWithDefaults result = builder.build();
   * }</pre>
   */
  @Override
  public OrderWithDefaults build() {
    OrderWithDefaults result = new OrderWithDefaults();
    this.id.ifSet(result::setId);
    this.priority.ifSet(result::setPriority).orElse(2);
    this.status.ifSet(result::setStatus).orElse("PENDING");
    return result;
  }

  /**
   * Returns a string representation of this builder, including only fields that have been set.
   * 
   * @return string representation of the builder
   */
  @Override
  public String toString() {
    return new ToStringBuilder(this, BuilderToStringStyle.INSTANCE).append("id", this.id)
        .append("priority", this.priority)
        .append("status", this.status)
        .toString();
  }

  /**
   * Interface that can be implemented by the DTO to provide fluent modification methods.
   */
  public interface With {
    /**
     * Initializes a builder from an instance of this class, using methods of this builder to change values and returns
     * the new built object.
     * 
     * @param b the consumer to apply modifications
     * @return the modified instance
     */
    default OrderWithDefaults with(Consumer<OrderWithDefaultsBuilder> b) {
      OrderWithDefaultsBuilder builder;
      try {
        builder = new OrderWithDefaultsBuilder(OrderWithDefaults.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'OrderWithDefaultsBuilder.With' should only be implemented by classes, which could be casted to 'OrderWithDefaults'",
            ex);
      }
      b.accept(builder);
      return builder.build();
    }

    /**
     * Creates a builder initialized from this instance.
     * 
     * @return a builder initialized with this instance's values
     */
    default OrderWithDefaultsBuilder with() {
      try {
        return new OrderWithDefaultsBuilder(OrderWithDefaults.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'OrderWithDefaultsBuilder.With' should only be implemented by classes, which could be casted to 'OrderWithDefaults'",
            ex);
      }
    }
  }
}