/*
 * MIT License
 *
 * Copyright (c) 2026 Andreas Igel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons with the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.javahelpers.simple.builders.processor.mapstruct;

import com.google.auto.service.AutoService;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import org.mapstruct.ap.spi.AccessorNamingStrategy;
import org.mapstruct.ap.spi.DefaultAccessorNamingStrategy;
import org.mapstruct.ap.spi.MapStructProcessingEnvironment;
import org.mapstruct.ap.spi.MethodType;

/**
 * MapStruct {@link AccessorNamingStrategy} that hides the generated helper methods of
 * simple-builders builders from bean mapping.
 *
 * <p>Generated builders carry convenience methods MapStruct must not treat as property setters:
 * differently-named helpers ({@code add2<Field>}, {@code <field>Update}, {@code conditional(...)})
 * would surface as phantom "unmapped target property" warnings, and same-named helper overloads
 * ({@code <field>(Supplier)}, {@code <field>(String, Object...)}, {@code <field>(Consumer)})
 * compete with the direct setter. For methods declared on a builder generated by simple-builders
 * this strategy returns {@link MethodType#OTHER} for everything that is not the direct property
 * setter ({@code <field><setterSuffix>} taking a single argument of the field type). Every other
 * type keeps the {@link DefaultAccessorNamingStrategy} behaviour.
 */
@AutoService(AccessorNamingStrategy.class)
public class MapStructAccessorNamingStrategy extends DefaultAccessorNamingStrategy {

  private static final String OPTION_PREFIX = "simplebuilder.";
  private static final String OPTION_USING_MAPSTRUCT = OPTION_PREFIX + "usingMapStructIntegration";
  private static final String DEFAULT_BUILDER_SUFFIX = "Builder";

  private AnnotationSupport annotations;
  private Map<String, String> processorOptions = Map.of();
  private final Map<String, Optional<Map<String, TypeMirror>>> directSettersCache = new HashMap<>();
  private boolean enabled = true;

  @Override
  public void init(MapStructProcessingEnvironment processingEnvironment) {
    super.init(processingEnvironment);
    annotations = new AnnotationSupport(processingEnvironment.getElementUtils());
    Map<String, String> options = processingEnvironment.getOptions();
    processorOptions = options == null ? Map.of() : options;
    // MapStruct forwards only its own options to SPI environments, so the off-switch follows the
    // simplebuilder.* convention and prefers the JVM system property
    enabled =
        !"false"
            .equalsIgnoreCase(
                AnnotationSupport.systemOption(processorOptions, OPTION_USING_MAPSTRUCT));
  }

  @Override
  public MethodType getMethodType(ExecutableElement method) {
    MethodType methodType = super.getMethodType(method);
    if (!enabled) {
      return methodType;
    }
    if (methodType != MethodType.SETTER && methodType != MethodType.ADDER) {
      return methodType;
    }
    if (!(method.getEnclosingElement() instanceof TypeElement builderType)) {
      return methodType;
    }
    Optional<Map<String, TypeMirror>> directSetters =
        directSettersCache.computeIfAbsent(
            builderType.getQualifiedName().toString(),
            ignored -> computeDirectSetters(builderType));
    if (directSetters.isEmpty() || isDirectSetter(method, directSetters.get())) {
      return methodType;
    }
    return MethodType.OTHER;
  }

  /**
   * Whether {@code method} is the direct property setter: it carries the configured setter name of
   * a bean field and takes exactly one argument assignable to that field's declared type.
   */
  private boolean isDirectSetter(ExecutableElement method, Map<String, TypeMirror> directSetters) {
    TypeMirror fieldType = directSetters.get(method.getSimpleName().toString());
    return fieldType != null
        && method.getParameters().size() == 1
        && typeUtils.isSameType(method.getParameters().get(0).asType(), fieldType);
  }

  /**
   * The direct property setters ({@code setter name -> field type}) of the bean {@code builderType}
   * was generated for, or empty when {@code builderType} is not a simple-builders builder.
   */
  private Optional<Map<String, TypeMirror>> computeDirectSetters(TypeElement builderType) {
    TypeElement beanElement = resolveBean(builderType);
    if (beanElement == null) {
      return Optional.empty();
    }
    String setterSuffix = resolveSetterSuffix(beanElement);
    Map<String, TypeMirror> directSetters = new HashMap<>();
    collectFields(beanElement, setterSuffix, directSetters);
    return Optional.of(directSetters);
  }

  /**
   * The bean a builder was generated for: {@code @BuilderImplementation(forClass = ...)} on the
   * builder, else the conventional name {@code <Bean><builderSuffix>} in the builder's package.
   */
  private TypeElement resolveBean(TypeElement builderType) {
    TypeMirror forClass = annotations.builderImplementationForClass(builderType);
    if (forClass instanceof DeclaredType declaredType
        && declaredType.asElement() instanceof TypeElement beanElement) {
      return beanElement;
    }
    String simpleName = builderType.getSimpleName().toString();
    String packageName = elementUtils.getPackageOf(builderType).getQualifiedName().toString();
    for (String suffix : builderSuffixCandidates()) {
      if (simpleName.endsWith(suffix) && simpleName.length() > suffix.length()) {
        TypeElement candidate =
            elementUtils.getTypeElement(
                packageName.isEmpty()
                    ? simpleName.substring(0, simpleName.length() - suffix.length())
                    : packageName
                        + "."
                        + simpleName.substring(0, simpleName.length() - suffix.length()));
        // Only a marked bean may claim the builder — otherwise a bean literally named
        // <X>Builder would hide its own non-field methods whenever a bean <X> exists.
        if (candidate != null && annotations.isBuilderGenerationTarget(candidate)) {
          return candidate;
        }
      }
    }
    return null;
  }

  /** Candidate builder name suffixes: the globally configured one plus the default. */
  private String[] builderSuffixCandidates() {
    String configured =
        AnnotationSupport.systemOption(processorOptions, OPTION_PREFIX + "builderSuffix");
    return configured != null && !configured.isEmpty()
        ? new String[] {configured, DEFAULT_BUILDER_SUFFIX}
        : new String[] {DEFAULT_BUILDER_SUFFIX};
  }

  /** The {@code setterSuffix} configured for {@code beanElement} ({@code ""} by default). */
  private String resolveSetterSuffix(TypeElement beanElement) {
    for (var optionsMirror : annotations.builderOptionsMirrors(beanElement)) {
      String setterSuffix = annotations.stringOption(optionsMirror, "setterSuffix");
      if (setterSuffix != null) {
        return setterSuffix;
      }
    }
    String global =
        AnnotationSupport.systemOption(processorOptions, OPTION_PREFIX + "setterSuffix");
    return global != null ? global : "";
  }

  /** Collects the bean's non-static fields incl. inherited ones into {@code directSetters}. */
  private void collectFields(
      TypeElement beanElement, String setterSuffix, Map<String, TypeMirror> directSetters) {
    for (Element member : beanElement.getEnclosedElements()) {
      if (member.getKind() == ElementKind.FIELD
          && member instanceof VariableElement field
          && !field.getModifiers().contains(Modifier.STATIC)) {
        directSetters.put(field.getSimpleName().toString() + setterSuffix, field.asType());
      }
    }
    TypeMirror superclass = beanElement.getSuperclass();
    if (superclass.getKind() == TypeKind.DECLARED
        && ((DeclaredType) superclass).asElement() instanceof TypeElement parent
        && !parent.getQualifiedName().contentEquals("java.lang.Object")) {
      collectFields(parent, setterSuffix, directSetters);
    }
  }
}
