/*
 * MIT License
 *
 * Copyright (c) 2026 Andreas Igel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons with the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.javahelpers.simple.builders.processor.mapstruct;

import com.google.auto.service.AutoService;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import org.javahelpers.simple.builders.processor.SimpleBuildersSpiIntegration;
import org.javahelpers.simple.builders.processor.SimpleBuildersSpiIntegration.PublishedBuilder;
import org.javahelpers.simple.builders.processor.model.type.BuilderInstantiation.StaticFactoryCall;
import org.mapstruct.ap.spi.BuilderInfo;
import org.mapstruct.ap.spi.BuilderProvider;
import org.mapstruct.ap.spi.MapStructProcessingEnvironment;
import org.mapstruct.ap.spi.TypeHierarchyErroneousException;

/**
 * MapStruct {@link BuilderProvider} SPI that makes MapStruct use builders generated by
 * simple-builders.
 *
 * <p>MapStruct's default provider only considers {@code public static} methods on the bean type
 * itself as builder-creation candidates. simple-builders keeps the factory on the generated builder
 * class ({@code PersonDtoBuilder.create()}), so beans are paired with builders exclusively through
 * the registry {@code BuilderProcessor} publishes — a constant-time lookup of already-resolved
 * {@link PublishedBuilder} descriptors (builder type, creation and build method, setter suffix),
 * covering custom packages and {@code @SimpleBuilderFor} targets. Builders produced by earlier
 * compilations are not discovered: only the beans the processor plans in the current run get
 * builder mapping.
 *
 * <p>While the compilation is not {@link SimpleBuildersSpiIntegration.State#FINISHED} the registry
 * may still grow, so a published builder that is not visible yet — or a bean marked for generation
 * whose entry may still arrive — defers the mapper via {@link TypeHierarchyErroneousException} to
 * the next processing round. After {@link SimpleBuildersSpiIntegration.State#FINISHED} a registry
 * miss is definitive and the lookup gracefully returns {@code null}.
 *
 * <p>The provider is registered via {@code META-INF/services} and is only loaded when
 * simple-builders-processor and mapstruct-processor share the annotation processor path. The
 * integration can be switched off entirely with {@code
 * -Asimplebuilder.usingMapStructIntegration=DISABLED} (resolved by {@code BuilderProcessor}, which
 * shares the classloader, or via the {@code -D} JVM system property).
 */
@AutoService(BuilderProvider.class)
public class MapStructBuilderProvider implements BuilderProvider {

  private static final String SIMPLE_BUILDER_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.SimpleBuilder";
  private static final String SIMPLE_BUILDER_TEMPLATE_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.SimpleBuilder.Template";
  private static final String IGNORE_4_BUILDER_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.Ignore4BuilderGeneration";

  private Elements elementUtils;
  private Map<String, String> processorOptions = Map.of();

  /** Resolved builder infos by bean qualified name; only positive results are cached. */
  private final Map<String, BuilderInfo> builderInfoCache = new HashMap<>();

  @Override
  public void init(MapStructProcessingEnvironment processingEnvironment) {
    // Ages out stale lifecycle state left by a previous compilation on a reused JVM.
    SimpleBuildersSpiIntegration.spiInitialized();
    this.elementUtils = processingEnvironment.getElementUtils();
    Map<String, String> options = processingEnvironment.getOptions();
    processorOptions = options == null ? Map.of() : options;
  }

  @Override
  public BuilderInfo findBuilderInfo(TypeMirror type) {
    if (SimpleBuildersSpiIntegration.isIntegrationDisabled(processorOptions)) {
      return null;
    }
    if (!(type instanceof DeclaredType declaredType)
        || !(declaredType.asElement() instanceof TypeElement beanElement)) {
      return null;
    }
    BuilderInfo cached = builderInfoCache.get(beanElement.getQualifiedName().toString());
    if (cached != null) {
      return cached;
    }
    BuilderInfo builderInfo = createBuilderInfo(beanElement);
    if (builderInfo != null) {
      builderInfoCache.put(beanElement.getQualifiedName().toString(), builderInfo);
    }
    return builderInfo;
  }

  private BuilderInfo createBuilderInfo(TypeElement beanElement) {
    Optional<PublishedBuilder> published =
        SimpleBuildersSpiIntegration.builderFor(beanElement.getQualifiedName().toString());
    TypeElement builderElement = findBuilderElement(beanElement, published);
    if (builderElement == null) {
      return null;
    }
    ExecutableElement creationMethod = creationMethod(builderElement, published.orElseThrow());
    List<ExecutableElement> buildMethod = buildMethod(builderElement, published.orElseThrow());
    if (creationMethod == null || buildMethod.isEmpty()) {
      return null;
    }
    return new BuilderInfo.Builder()
        .builderCreationMethod(creationMethod)
        .buildMethod(buildMethod)
        .build();
  }

  /**
   * Locates the generated builder for {@code beanElement} through the registry {@code
   * BuilderProcessor} publishes — the list decides alone which type is claimed.
   */
  private TypeElement findBuilderElement(
      TypeElement beanElement, Optional<PublishedBuilder> published) {
    if (published.isEmpty()) {
      if (SimpleBuildersSpiIntegration.state() != SimpleBuildersSpiIntegration.State.FINISHED
          && isBuilderGenerationTarget(beanElement)) {
        // Marked for generation but not published yet — MapStruct may run ahead of this
        // processor's round; defer so the registry can fill in before the mapper is generated.
        throw new TypeHierarchyErroneousException(beanElement.asType());
      }
      return null;
    }
    TypeElement builderElement =
        elementUtils.getTypeElement(published.get().builder().typeName().getFullQualifiedName());
    if (builderElement == null
        && SimpleBuildersSpiIntegration.state() != SimpleBuildersSpiIntegration.State.FINISHED) {
      // Published but not emitted yet — defer so the mapper retries once the type exists.
      throw new TypeHierarchyErroneousException(beanElement.asType());
    }
    return builderElement;
  }

  /**
   * The published creation method on the resolved builder — a {@code public static} parameterless
   * factory whose name the descriptor carries ({@code create} for generated builders).
   */
  private ExecutableElement creationMethod(TypeElement builderElement, PublishedBuilder published) {
    if (!(published.builder().funcForEmptyBuilder() instanceof StaticFactoryCall factory)) {
      return null;
    }
    return findMethod(builderElement, factory.methodName(), Modifier.PUBLIC, Modifier.STATIC);
  }

  /**
   * The published build method on the resolved builder — the {@code public} parameterless instance
   * method named by the descriptor ({@code build} for generated builders).
   */
  private List<ExecutableElement> buildMethod(
      TypeElement builderElement, PublishedBuilder published) {
    ExecutableElement method =
        findMethod(builderElement, published.builder().buildMethodName(), Modifier.PUBLIC);
    return method == null ? List.of() : List.of(method);
  }

  /** The parameterless method with {@code name} and all {@code requiredModifiers} on the type. */
  private ExecutableElement findMethod(
      TypeElement typeElement, String name, Modifier... requiredModifiers) {
    for (Element member : typeElement.getEnclosedElements()) {
      if (member.getKind() == ElementKind.METHOD
          && member instanceof ExecutableElement method
          && method.getSimpleName().contentEquals(name)
          && method.getParameters().isEmpty()
          && method.getModifiers().containsAll(List.of(requiredModifiers))) {
        return method;
      }
    }
    return null;
  }

  /**
   * Whether {@code beanElement} is marked for builder generation ({@code @SimpleBuilder} or a
   * builder template annotation, not opted out via {@code @Ignore4BuilderGeneration}). The marker
   * only decides deferral — it never decides which type is claimed.
   */
  private boolean isBuilderGenerationTarget(TypeElement beanElement) {
    boolean marked = false;
    for (AnnotationMirror mirror : elementUtils.getAllAnnotationMirrors(beanElement)) {
      String annotationName =
          ((TypeElement) mirror.getAnnotationType().asElement()).getQualifiedName().toString();
      if (annotationName.equals(IGNORE_4_BUILDER_ANNOTATION)) {
        return false;
      }
      if (annotationName.equals(SIMPLE_BUILDER_ANNOTATION)) {
        marked = true;
        continue;
      }
      // A custom builder template annotation (e.g. @SimpleMinimalBuilder or a project-defined
      // one): its type is meta-annotated with @SimpleBuilder.Template.
      for (AnnotationMirror metaMirror :
          mirror.getAnnotationType().asElement().getAnnotationMirrors()) {
        if (((TypeElement) metaMirror.getAnnotationType().asElement())
            .getQualifiedName()
            .contentEquals(SIMPLE_BUILDER_TEMPLATE_ANNOTATION)) {
          marked = true;
          break;
        }
      }
    }
    return marked;
  }
}
