/*
 * MIT License
 *
 * Copyright (c) 2026 Andreas Igel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons with the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.javahelpers.simple.builders.processor.mapstruct;

import com.google.auto.service.AutoService;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import org.javahelpers.simple.builders.core.annotations.Ignore4BuilderGeneration;
import org.javahelpers.simple.builders.core.annotations.SimpleBuilder;
import org.javahelpers.simple.builders.processor.SimpleBuildersSpiIntegration;
import org.javahelpers.simple.builders.processor.SimpleBuildersSpiIntegration.PublishedBuilder;
import org.javahelpers.simple.builders.processor.SimpleBuildersSpiIntegration.State;
import org.javahelpers.simple.builders.processor.analysis.JavaLangAnalyser;
import org.javahelpers.simple.builders.processor.model.type.BuilderInstantiation.StaticFactoryCall;
import org.mapstruct.ap.spi.BuilderInfo;
import org.mapstruct.ap.spi.BuilderProvider;
import org.mapstruct.ap.spi.MapStructProcessingEnvironment;
import org.mapstruct.ap.spi.TypeHierarchyErroneousException;

/**
 * MapStruct {@link BuilderProvider} SPI that makes MapStruct use builders generated by
 * simple-builders.
 *
 * <p>MapStruct's default provider only considers {@code public static} methods on the bean type
 * itself as builder-creation candidates. simple-builders keeps the factory on the generated builder
 * class ({@code PersonDtoBuilder.create()}), so beans are paired with builders exclusively through
 * the registry {@code BuilderProcessor} publishes — a constant-time lookup of already-resolved
 * {@link PublishedBuilder} descriptors (builder type, creation and build method, setter suffix),
 * covering custom packages and {@code @SimpleBuilderFor} targets. Builders produced by earlier
 * compilations are not discovered: only the beans the processor plans in the current run get
 * builder mapping.
 *
 * <p>A registry miss for a bean marked for generation ({@code @SimpleBuilder} or a template
 * annotation) defers the mapper via {@link TypeHierarchyErroneousException} while {@link
 * State#INIT} or {@link State#PROCESSING} hold — MapStruct may run ahead of this processor's first
 * round. From {@link State#TARGETS_REGISTERED} on, an unregistered bean was skipped by planning or
 * is foreign and resolves to no builder; at {@link State#FINISHED} a marked bean that was never
 * registered is reported as a warning. A published builder whose type is not emitted yet defers
 * until {@link State#FINISHED}.
 *
 * <p>The provider is registered via {@code META-INF/services} and is only loaded when
 * simple-builders-processor and mapstruct-processor share the annotation processor path. The
 * integration can be switched off entirely with {@code
 * -Asimplebuilder.usingMapStructIntegration=DISABLED} (resolved by {@code BuilderProcessor}, which
 * shares the classloader, or via the {@code -D} JVM system property).
 */
@AutoService(BuilderProvider.class)
public class MapStructBuilderProvider implements BuilderProvider {

  private Elements elementUtils;
  private Map<String, String> processorOptions = Map.of();

  /** Resolved builder infos by bean qualified name; only positive results are cached. */
  private final Map<String, BuilderInfo> builderInfoCache = new HashMap<>();

  @Override
  public void init(MapStructProcessingEnvironment processingEnvironment) {
    this.elementUtils = processingEnvironment.getElementUtils();
    Map<String, String> options = processingEnvironment.getOptions();
    processorOptions = options == null ? Map.of() : options;
  }

  @Override
  public BuilderInfo findBuilderInfo(TypeMirror type) {
    if (!SimpleBuildersSpiIntegration.isMapstructGenerationEnabled(
        elementUtils, processorOptions)) {
      return null;
    }
    if (!(type instanceof DeclaredType declaredType)
        || !(declaredType.asElement() instanceof TypeElement beanElement)) {
      return null;
    }
    BuilderInfo cached = builderInfoCache.get(beanElement.getQualifiedName().toString());
    if (cached != null) {
      return cached;
    }
    BuilderInfo builderInfo = createBuilderInfo(beanElement);
    if (builderInfo != null) {
      builderInfoCache.put(beanElement.getQualifiedName().toString(), builderInfo);
    }
    return builderInfo;
  }

  /**
   * Resolves the generated builder for {@code beanElement} through the registry {@code
   * BuilderProcessor} publishes — the list decides alone which type is claimed.
   */
  private BuilderInfo createBuilderInfo(TypeElement beanElement) {
    Optional<PublishedBuilder> published = publishedFor(beanElement);
    TypeElement builderElement = findBuilderElement(beanElement, published);
    if (builderElement == null) {
      return null;
    }
    ExecutableElement creationMethod = creationMethod(builderElement, published.orElseThrow());
    Optional<ExecutableElement> buildMethod = buildMethod(builderElement, published.orElseThrow());
    if (creationMethod == null || buildMethod.isEmpty()) {
      return null;
    }
    return new BuilderInfo.Builder()
        .builderCreationMethod(creationMethod)
        .buildMethod(List.of(buildMethod.orElseThrow()))
        .build();
  }

  /**
   * The element of the builder published for {@code beanElement}, waiting for a pending
   * registration or emission via {@link TypeHierarchyErroneousException} — MapStruct's own deferral
   * mechanism. {@code null} for foreign beans and for misses that are definitive.
   */
  private TypeElement findBuilderElement(
      TypeElement beanElement, Optional<PublishedBuilder> published) {
    boolean markedForGeneration = isBuilderGenerationTarget(beanElement);
    if (published.isEmpty()) {
      if (!markedForGeneration) {
        // Foreign bean — never claimed, never deferred.
        return null;
      }
      return switch (state()) {
        // Marked but not published yet — MapStruct may run ahead of this processor's first
        // round; defer so the registry can fill in before the mapper is generated.
        case INIT, PROCESSING -> throw new TypeHierarchyErroneousException(beanElement.asType());
        // Initial targets are registered — a marked bean without an entry was skipped by
        // planning; it maps without a builder.
        case TARGETS_REGISTERED -> null;
        case FINISHED -> {
          warnMarkedBeanWithoutRegisteredBuilder(beanElement);
          yield null;
        }
      };
    }
    TypeElement builderElement =
        elementUtils.getTypeElement(published.get().builder().typeName().getFullQualifiedName());
    if (builderElement == null
        && !SimpleBuildersSpiIntegration.isSimpleBuildersFinishedForIntegration()) {
      // Published but not emitted yet — defer so the mapper retries once the type exists.
      throw new TypeHierarchyErroneousException(beanElement.asType());
    }
    return builderElement;
  }

  /**
   * The state of the compilation this provider's {@code elementUtils} belongs to — {@link
   * State#INIT} while the holder still describes a previous run on a reused JVM.
   */
  private State state() {
    return SimpleBuildersSpiIntegration.isCurrentCompilation(elementUtils)
        ? SimpleBuildersSpiIntegration.state()
        : State.INIT;
  }

  /**
   * The builder published for {@code beanElement} — empty while the holder still describes a
   * previous run, so stale entries can never claim a bean.
   */
  private Optional<PublishedBuilder> publishedFor(TypeElement beanElement) {
    return SimpleBuildersSpiIntegration.isCurrentCompilation(elementUtils)
        ? SimpleBuildersSpiIntegration.builderFor(beanElement.getQualifiedName().toString())
        : Optional.empty();
  }

  /** Warns that a bean marked for generation got no registered builder in this compilation. */
  private void warnMarkedBeanWithoutRegisteredBuilder(TypeElement beanElement) {
    // SPI environments expose no Messager — stderr is the only channel a build shows.
    System.err.println(
        "simple-builders: WARNING: no generated builder was registered for the marked bean '"
            + beanElement.getQualifiedName()
            + "'; MapStruct maps it without a builder.");
  }

  /**
   * The published creation method on the resolved builder — a {@code public static} parameterless
   * factory whose name the descriptor carries ({@code create} for generated builders).
   */
  private ExecutableElement creationMethod(TypeElement builderElement, PublishedBuilder published) {
    if (!(published.builder().funcForEmptyBuilder() instanceof StaticFactoryCall factory)) {
      return null;
    }
    return JavaLangAnalyser.findMethodWithoutParameters(
            builderElement, factory.methodName(), Modifier.PUBLIC, Modifier.STATIC)
        .orElse(null);
  }

  /**
   * The published build method on the resolved builder — the {@code public} parameterless instance
   * method named by the descriptor ({@code build} for generated builders).
   */
  private Optional<ExecutableElement> buildMethod(
      TypeElement builderElement, PublishedBuilder published) {
    return JavaLangAnalyser.findMethodWithoutParameters(
        builderElement, published.builder().buildMethodName(), Modifier.PUBLIC);
  }

  /**
   * Whether {@code beanElement} is marked for builder generation ({@code @SimpleBuilder} or a
   * builder template annotation, not opted out via {@code @Ignore4BuilderGeneration}). The marker
   * only decides deferral and the finished-state warning — it never decides which type is claimed.
   */
  private boolean isBuilderGenerationTarget(TypeElement beanElement) {
    if (JavaLangAnalyser.findAnnotation(beanElement, Ignore4BuilderGeneration.class).isPresent()) {
      return false;
    }
    if (JavaLangAnalyser.findAnnotation(beanElement, SimpleBuilder.class).isPresent()) {
      return true;
    }
    for (AnnotationMirror mirror : beanElement.getAnnotationMirrors()) {
      // A custom builder template annotation (e.g. @SimpleMinimalBuilder or a project-defined
      // one): its type is meta-annotated with @SimpleBuilder.Template.
      if (JavaLangAnalyser.findAnnotation(
              mirror.getAnnotationType().asElement(), SimpleBuilder.Template.class)
          .isPresent()) {
        return true;
      }
    }
    return false;
  }
}
