/*
 * MIT License
 *
 * Copyright (c) 2026 Andreas Igel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons with the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.javahelpers.simple.builders.processor.mapstruct;

import com.google.auto.service.AutoService;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import org.mapstruct.ap.spi.BuilderInfo;
import org.mapstruct.ap.spi.BuilderProvider;
import org.mapstruct.ap.spi.MapStructProcessingEnvironment;
import org.mapstruct.ap.spi.TypeHierarchyErroneousException;

/**
 * MapStruct {@link BuilderProvider} SPI that makes MapStruct use builders generated by
 * simple-builders.
 *
 * <p>MapStruct's default provider only considers {@code public static} methods on the bean type
 * itself as builder-creation candidates. simple-builders keeps the factory on the generated builder
 * class ({@code PersonDtoBuilder.create()}), so the generated builders are found here by scanning
 * the target package for types carrying {@code @BuilderImplementation(forClass = <bean>)} and by
 * resolving the conventional name {@code <Bean><builderSuffix>} in the target package.
 *
 * <p>The provider is registered via {@code META-INF/services} and is only loaded when
 * simple-builders-processor and mapstruct-processor share the annotation processor path.
 */
@AutoService(BuilderProvider.class)
public class SimpleBuildersBuilderProvider implements BuilderProvider {

  private static final String DEFAULT_BUILDER_SUFFIX = "Builder";
  private static final String SIMPLE_BUILDER_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.SimpleBuilder";
  private static final String SIMPLE_BUILDER_TEMPLATE_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.SimpleBuilder.Template";
  private static final String BUILDER_IMPLEMENTATION_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.BuilderImplementation";
  private static final String IGNORE_4_BUILDER_ANNOTATION =
      "org.javahelpers.simple.builders.core.annotations.Ignore4BuilderGeneration";

  private Elements elementUtils;
  private Types typeUtils;

  @Override
  public void init(MapStructProcessingEnvironment processingEnvironment) {
    this.elementUtils = processingEnvironment.getElementUtils();
    this.typeUtils = processingEnvironment.getTypeUtils();
  }

  @Override
  public BuilderInfo findBuilderInfo(TypeMirror type) {
    if (!(type instanceof DeclaredType declaredType)
        || !(declaredType.asElement() instanceof TypeElement beanElement)) {
      return null;
    }

    TypeElement builderElement = findBuilderElement(beanElement);
    if (builderElement == null) {
      if (isBuilderGenerationTarget(beanElement)) {
        // The bean is annotated for builder generation but the builder does not exist yet in this
        // processing round. Throwing defers mapper generation to the next round.
        throw new TypeHierarchyErroneousException(type);
      }
      return null;
    }

    ExecutableElement creationMethod = findCreationMethod(builderElement);
    List<ExecutableElement> buildMethods = findBuildMethods(builderElement, type);
    if (creationMethod == null || buildMethods.isEmpty()) {
      return null;
    }
    return new BuilderInfo.Builder()
        .builderCreationMethod(creationMethod)
        .buildMethod(buildMethods)
        .build();
  }

  /**
   * Locates the generated builder for {@code beanElement}: first by {@code @BuilderImplementation}
   * in the candidate packages, then by conventional name {@code <Bean><builderSuffix>}.
   */
  private TypeElement findBuilderElement(TypeElement beanElement) {
    List<String> packageNames = candidatePackageNames(beanElement);

    // Primary: builders generated by simple-builders carry
    // @BuilderImplementation(forClass = <bean>) by default.
    for (String packageName : packageNames) {
      PackageElement packageElement = elementUtils.getPackageElement(packageName);
      if (packageElement == null) {
        continue;
      }
      for (Element member : packageElement.getEnclosedElements()) {
        if (member instanceof TypeElement typeElement
            && isGeneratedBuilderFor(typeElement, beanElement)) {
          return typeElement;
        }
      }
    }

    // Fallback for builders generated with usingBuilderImplementationAnnotation disabled:
    // resolve <Bean><builderSuffix> by name and verify the type looks like a builder.
    for (String packageName : packageNames) {
      for (String suffix : candidateSuffixes(beanElement)) {
        TypeElement candidate =
            elementUtils.getTypeElement(
                qualifiedName(packageName, beanElement.getSimpleName() + suffix));
        if (candidate != null
            && findCreationMethod(candidate) != null
            && !findBuildMethods(candidate, beanElement.asType()).isEmpty()) {
          return candidate;
        }
      }
    }
    return null;
  }

  /**
   * Checks whether {@code candidate} is annotated {@code @BuilderImplementation(forClass =
   * beanElement)}.
   */
  private boolean isGeneratedBuilderFor(TypeElement candidate, TypeElement beanElement) {
    for (AnnotationMirror mirror : candidate.getAnnotationMirrors()) {
      if (!qualifiedNameOf(mirror).equals(BUILDER_IMPLEMENTATION_ANNOTATION)) {
        continue;
      }
      for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry :
          elementUtils.getElementValuesWithDefaults(mirror).entrySet()) {
        if (entry.getKey().getSimpleName().contentEquals("forClass")
            && entry.getValue().getValue() instanceof TypeMirror forClass
            && typeUtils.isSameType(
                typeUtils.erasure(forClass), typeUtils.erasure(beanElement.asType()))) {
          return true;
        }
      }
      // @BuilderImplementation present but forClass points at another bean
      return false;
    }
    return false;
  }

  /** Packages the generated builder may live in: the bean's package or a configured packageName. */
  private List<String> candidatePackageNames(TypeElement beanElement) {
    List<String> packageNames = new ArrayList<>();
    packageNames.add(elementUtils.getPackageOf(beanElement).getQualifiedName().toString());
    for (AnnotationMirror optionsMirror : builderOptionsMirrors(beanElement)) {
      String packageName = stringOption(optionsMirror, "packageName");
      if (packageName != null && !packageName.isEmpty() && !packageNames.contains(packageName)) {
        packageNames.add(packageName);
      }
    }
    return packageNames;
  }

  /** Builder name suffixes to try: explicitly configured ones plus the default. */
  private List<String> candidateSuffixes(TypeElement beanElement) {
    List<String> suffixes = new ArrayList<>();
    for (AnnotationMirror optionsMirror : builderOptionsMirrors(beanElement)) {
      String suffix = stringOption(optionsMirror, "builderSuffix");
      if (suffix != null && !suffix.isEmpty() && !suffixes.contains(suffix)) {
        suffixes.add(suffix);
      }
    }
    if (!suffixes.contains(DEFAULT_BUILDER_SUFFIX)) {
      suffixes.add(DEFAULT_BUILDER_SUFFIX);
    }
    return suffixes;
  }

  /**
   * Options mirrors relevant for builder generation on {@code beanElement}: {@code options()} of
   * {@code @SimpleBuilder} and of {@code @SimpleBuilder.Template} on builder template annotations.
   */
  private List<AnnotationMirror> builderOptionsMirrors(TypeElement beanElement) {
    List<AnnotationMirror> optionsMirrors = new ArrayList<>();
    for (AnnotationMirror mirror : elementUtils.getAllAnnotationMirrors(beanElement)) {
      String annotationName = qualifiedNameOf(mirror);
      if (annotationName.equals(SIMPLE_BUILDER_ANNOTATION)) {
        addOptionsMirror(mirror, optionsMirrors);
      } else {
        // A custom builder template: read options of its @SimpleBuilder.Template meta-annotation.
        Element annotationType = mirror.getAnnotationType().asElement();
        for (AnnotationMirror metaMirror : annotationType.getAnnotationMirrors()) {
          if (qualifiedNameOf(metaMirror).equals(SIMPLE_BUILDER_TEMPLATE_ANNOTATION)) {
            addOptionsMirror(metaMirror, optionsMirrors);
          }
        }
      }
    }
    return optionsMirrors;
  }

  private void addOptionsMirror(AnnotationMirror mirror, List<AnnotationMirror> optionsMirrors) {
    for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry :
        elementUtils.getElementValuesWithDefaults(mirror).entrySet()) {
      if (entry.getKey().getSimpleName().contentEquals("options")
          && entry.getValue().getValue() instanceof AnnotationMirror optionsMirror) {
        optionsMirrors.add(optionsMirror);
      }
    }
  }

  private String stringOption(AnnotationMirror optionsMirror, String name) {
    for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry :
        elementUtils.getElementValuesWithDefaults(optionsMirror).entrySet()) {
      if (entry.getKey().getSimpleName().contentEquals(name)) {
        Object value = entry.getValue().getValue();
        if (value instanceof String stringValue) {
          return stringValue;
        }
      }
    }
    return null;
  }

  /**
   * Whether {@code beanElement} is marked for builder generation ({@code @SimpleBuilder} or a
   * builder template annotation, not opted out via {@code @Ignore4BuilderGeneration}).
   */
  private boolean isBuilderGenerationTarget(TypeElement beanElement) {
    List<? extends AnnotationMirror> mirrors = elementUtils.getAllAnnotationMirrors(beanElement);
    for (AnnotationMirror mirror : mirrors) {
      if (qualifiedNameOf(mirror).equals(IGNORE_4_BUILDER_ANNOTATION)) {
        return false;
      }
    }
    for (AnnotationMirror mirror : mirrors) {
      if (qualifiedNameOf(mirror).equals(SIMPLE_BUILDER_ANNOTATION)) {
        return true;
      }
      // A custom builder template annotation (e.g. @SimpleMinimalBuilder or a project-defined
      // one): its type is meta-annotated with @SimpleBuilder.Template.
      Element annotationType = mirror.getAnnotationType().asElement();
      for (AnnotationMirror metaMirror : annotationType.getAnnotationMirrors()) {
        if (qualifiedNameOf(metaMirror).equals(SIMPLE_BUILDER_TEMPLATE_ANNOTATION)) {
          return true;
        }
      }
    }
    return false;
  }

  /**
   * A {@code public static} parameterless method on the builder returning the builder type, e.g.
   * {@code create()}.
   */
  private ExecutableElement findCreationMethod(TypeElement builderElement) {
    List<ExecutableElement> candidates = new ArrayList<>();
    for (Element member : builderElement.getEnclosedElements()) {
      if (member.getKind() == ElementKind.METHOD
          && member instanceof ExecutableElement method
          && method.getParameters().isEmpty()
          && method.getModifiers().contains(Modifier.PUBLIC)
          && method.getModifiers().contains(Modifier.STATIC)
          && isBuilderType(method.getReturnType(), builderElement)) {
        candidates.add(method);
      }
    }
    // Prefer the simple-builders convention ("create"); otherwise use the single candidate.
    for (ExecutableElement candidate : candidates) {
      if (candidate.getSimpleName().contentEquals("create")) {
        return candidate;
      }
    }
    return candidates.size() == 1 ? candidates.get(0) : null;
  }

  /**
   * {@code public} parameterless instance methods on the builder returning the bean type, e.g.
   * {@code build()}.
   */
  private List<ExecutableElement> findBuildMethods(
      TypeElement builderElement, TypeMirror beanType) {
    List<ExecutableElement> buildMethods = new ArrayList<>();
    for (Element member : builderElement.getEnclosedElements()) {
      if (member.getKind() == ElementKind.METHOD
          && member instanceof ExecutableElement method
          && method.getParameters().isEmpty()
          && method.getModifiers().contains(Modifier.PUBLIC)
          && !method.getModifiers().contains(Modifier.STATIC)
          && typeUtils.isSameType(
              typeUtils.erasure(method.getReturnType()), typeUtils.erasure(beanType))) {
        buildMethods.add(method);
      }
    }
    return buildMethods;
  }

  private boolean isBuilderType(TypeMirror type, TypeElement builderElement) {
    return typeUtils.isSameType(
        typeUtils.erasure(type), typeUtils.erasure(builderElement.asType()));
  }

  private String qualifiedNameOf(AnnotationMirror mirror) {
    return ((TypeElement) mirror.getAnnotationType().asElement()).getQualifiedName().toString();
  }

  private static String qualifiedName(String packageName, CharSequence simpleName) {
    return packageName.isEmpty() ? simpleName.toString() : packageName + "." + simpleName;
  }
}
