/*
 * MIT License
 *
 * Copyright (c) 2026 Andreas Igel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.javahelpers.simple.builders.processor.model.core;

import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import org.javahelpers.simple.builders.core.enums.AccessModifier;
import org.javahelpers.simple.builders.processor.model.annotation.AnnotationDto;
import org.javahelpers.simple.builders.processor.model.annotation.InterfaceName;
import org.javahelpers.simple.builders.processor.model.imports.ImportStatement;
import org.javahelpers.simple.builders.processor.model.imports.RegularImport;
import org.javahelpers.simple.builders.processor.model.imports.StaticImport;
import org.javahelpers.simple.builders.processor.model.javadoc.JavadocDto;
import org.javahelpers.simple.builders.processor.model.method.BuilderMethodDto;
import org.javahelpers.simple.builders.processor.model.method.ConstructorDto;
import org.javahelpers.simple.builders.processor.model.type.BuilderNestedTypeDto;
import org.javahelpers.simple.builders.processor.model.type.GenericParameterDto;
import org.javahelpers.simple.builders.processor.model.type.TypeName;
import org.javahelpers.simple.builders.processor.model.type.TypeNameArray;
import org.javahelpers.simple.builders.processor.model.type.TypeNameGeneric;

/**
 * Generation-side DTO holding all information for generating a builder.
 *
 * <p>This class does NOT extend {@link GenerationTargetClassDto}. Instead, it holds generation-side
 * data (including {@link BuilderMethodDto} and {@link BuilderNestedTypeDto}) and produces a {@link
 * GenerationTargetClassDto} (rendering DTO) during finalization in {@code
 * BuilderDefinitionCreator.finalizeDefinition()}.
 */
public class BuilderDefinitionDto {

  // --- Builder-specific fields ---

  /** Target type of result of building by builder. Containing package and name of DTO. */
  private TypeName buildingTargetTypeName;

  /**
   * Fields in constructor. Containing all fields which need to be given for calling the
   * constructor. Ordering in LinkedList is matching ordering of parameters in constructor call.
   * Instances of fields are added in LinkedList of all fields too.
   */
  private final List<FieldDto> fieldsInConstructor = new LinkedList<>();

  /**
   * List of all fields of target DTO which are supported by builder. A field could be supported by
   * multiple functions in builder.
   */
  private final List<FieldDto> fields = new LinkedList<>();

  /** Configuration for builder generation. */
  private BuilderConfiguration configuration;

  // --- Rendering-side fields (set during enhancement, mapped during finalization) ---

  /** Generated class FQN. */
  private TypeName typeName;

  /** Class visibility. */
  private AccessModifier classAccessModifier;

  /** Superclass, null if none. */
  private TypeName superType;

  /** Field declarations. */
  private final List<ClassFieldDto> classFields = new LinkedList<>();

  /** Constructor definitions. */
  private final List<ConstructorDto> constructors = new LinkedList<>();

  /**
   * Builder-level methods generated by enhancers (not tied to a specific field). These are
   * BuilderMethodDto instances that will be mapped to MethodDto during finalization.
   */
  private final List<BuilderMethodDto> methods = new LinkedList<>();

  /** Generic parameters declared on the target DTO (e.g., {@code <T extends Number, U>}). */
  private final List<GenericParameterDto> generics = new LinkedList<>();

  /** Imports (both regular and static imports). */
  private final Set<ImportStatement> imports = new LinkedHashSet<>();

  /**
   * Nested types generated by enhancers (generation-side). These are BuilderNestedTypeDto instances
   * that will be mapped to NestedTypeDto during finalization.
   */
  private final List<BuilderNestedTypeDto> nestedTypes = new LinkedList<>();

  /** Class-level annotations. */
  private final Set<AnnotationDto> classAnnotations = new LinkedHashSet<>();

  /** Interfaces to be implemented by the generated builder class. */
  private final Set<InterfaceName> interfaces = new LinkedHashSet<>();

  /** Class-level JavaDoc for the generated builder class. */
  private JavadocDto classJavadoc;

  /**
   * Getting type of builder.
   *
   * @return package and name of builder.
   */
  public TypeName getBuilderTypeName() {
    return typeName;
  }

  /**
   * Setting type of builder.
   *
   * @param builderClassName type of builder
   */
  public void setBuilderTypeName(TypeName builderClassName) {
    this.typeName = builderClassName;
  }

  public TypeName getTypeName() {
    return typeName;
  }

  public void setTypeName(TypeName typeName) {
    this.typeName = typeName;
  }

  public AccessModifier getClassAccessModifier() {
    return classAccessModifier;
  }

  public void setClassAccessModifier(AccessModifier classAccessModifier) {
    this.classAccessModifier = classAccessModifier;
  }

  public TypeName getSuperType() {
    return superType;
  }

  public void setSuperType(TypeName superType) {
    this.superType = superType;
  }

  public List<ClassFieldDto> getClassFields() {
    return classFields;
  }

  public void addClassField(ClassFieldDto classField) {
    this.classFields.add(classField);
  }

  public List<ConstructorDto> getConstructors() {
    return constructors;
  }

  public void addConstructor(ConstructorDto constructor) {
    this.constructors.add(constructor);
  }

  public Set<ImportStatement> getImports() {
    return imports;
  }

  public void addImport(ImportStatement importStatement) {
    this.imports.add(importStatement);
  }

  public void addImport(Class<?> clazz) {
    addImport(new RegularImport(TypeName.of(clazz)));
  }

  public void addImport(TypeName typeName) {
    if (typeName instanceof TypeNameGeneric generic) {
      addImport(generic.getRawType());
      generic.getInnerTypeArguments().forEach(this::addImport);
    } else if (typeName instanceof TypeNameArray array) {
      addImport(array.getTypeOfArray());
    } else {
      addImport(new RegularImport(typeName));
    }
  }

  public void addStaticImport(Class<?> clazz, String memberName) {
    addImport(new StaticImport(TypeName.of(clazz), memberName));
  }

  public void addStaticImport(TypeName type, String memberName) {
    TypeName typeRaw = new TypeName(type.getPackageName(), type.getClassName());
    addImport(new StaticImport(typeRaw, memberName));
  }

  public void addGeneric(GenericParameterDto generic) {
    generics.add(generic);
  }

  public List<GenericParameterDto> getGenerics() {
    return generics;
  }

  public Set<AnnotationDto> getClassAnnotations() {
    return classAnnotations;
  }

  public void addClassAnnotation(AnnotationDto annotation) {
    this.classAnnotations.add(annotation);
  }

  public Set<InterfaceName> getInterfaces() {
    return interfaces;
  }

  public void addInterface(InterfaceName interfaceType) {
    this.interfaces.add(interfaceType);
  }

  public JavadocDto getClassJavadoc() {
    return classJavadoc;
  }

  public void setClassJavadoc(JavadocDto classJavadoc) {
    this.classJavadoc = classJavadoc;
  }

  /**
   * Getting target type of result of building by builder.
   *
   * @return package and name of type of building result.
   */
  public TypeName getBuildingTargetTypeName() {
    return buildingTargetTypeName;
  }

  /**
   * Setting target type of result of building by builder.
   *
   * @param buildingTargetTypeName package and name of type of building result
   */
  public void setBuildingTargetTypeName(TypeName buildingTargetTypeName) {
    this.buildingTargetTypeName = buildingTargetTypeName;
  }

  /**
   * Adding a field-definition to builder definition.
   *
   * @param field to be added
   */
  public void addField(FieldDto field) {
    fields.add(field);
  }

  /**
   * Adds a field definition that will be provided via the DTO constructor.
   *
   * @param field the field to add to the constructor parameters
   */
  public void addFieldInConstructor(FieldDto field) {
    fieldsInConstructor.add(field);
  }

  /**
   * Adds multiple field definitions to be provided via the DTO constructor.
   *
   * @param fields the list of fields to add to the constructor parameters
   */
  public void addAllFieldsInConstructor(List<FieldDto> fields) {
    fieldsInConstructor.addAll(fields);
  }

  /**
   * Adds multiple field definitions to the builder.
   *
   * @param fields the list of fields to add
   */
  public void addAllFields(List<FieldDto> fields) {
    this.fields.addAll(fields);
  }

  /**
   * Getting all defined fields in builder definition.
   *
   * @return list of fields
   */
  public List<FieldDto> getSetterFieldsForBuilder() {
    return fields;
  }

  /**
   * Returns the ordered list of fields to be passed to the DTO constructor.
   *
   * @return the ordered list of constructor parameter fields
   */
  public List<FieldDto> getConstructorFieldsForBuilder() {
    return fieldsInConstructor;
  }

  /**
   * Returns all fields known to the builder in a single list. Constructor parameters appear first
   * (in constructor order), followed by setter-derived fields.
   *
   * @return all fields in the builder (constructor fields first, then setter fields)
   */
  public List<FieldDto> getAllFieldsForBuilder() {
    LinkedList<FieldDto> all = new LinkedList<>();
    all.addAll(fieldsInConstructor);
    all.addAll(fields);
    return all;
  }

  /**
   * Returns the configuration for builder generation.
   *
   * @return the builder configuration
   */
  public BuilderConfiguration getConfiguration() {
    return configuration;
  }

  /**
   * Sets the builder configuration.
   *
   * @param configuration the builder configuration
   */
  public void setConfiguration(BuilderConfiguration configuration) {
    this.configuration = configuration;
  }

  /**
   * Adds a builder-level method generated by an enhancer.
   *
   * @param method the builder method to add
   */
  public void addMethod(BuilderMethodDto method) {
    this.methods.add(method);
  }

  /**
   * Returns all builder-level methods added by enhancers.
   *
   * @return list of builder-level methods
   */
  public List<BuilderMethodDto> getMethods() {
    return methods;
  }

  /**
   * Adds a nested type generated by an enhancer.
   *
   * @param nestedType the nested type to add
   */
  public void addNestedType(BuilderNestedTypeDto nestedType) {
    this.nestedTypes.add(nestedType);
  }

  /**
   * Returns all nested types added by enhancers.
   *
   * @return list of nested types
   */
  public List<BuilderNestedTypeDto> getNestedTypes() {
    return nestedTypes;
  }
}
