package org.javahelpers.simple.builders.example.scoping;

import static org.javahelpers.simple.builders.core.util.TrackedValue.changedValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.initialValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.unsetValue;
import java.util.function.BooleanSupplier;
import java.util.function.Consumer;
import java.util.function.Supplier;
import javax.annotation.processing.Generated;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.javahelpers.simple.builders.core.annotations.BuilderImplementation;
import org.javahelpers.simple.builders.core.interfaces.IBuilderBase;
import org.javahelpers.simple.builders.core.util.BuilderToStringStyle;
import org.javahelpers.simple.builders.core.util.TrackedValue;
import org.javahelpers.simple.builders.example.SponsorDto;
import org.javahelpers.simple.builders.example.library.LibraryHelperDto;

/**
 * Builder for {@code org.javahelpers.simple.builders.example.scoping.ScopedOwnerDto}.
 * <p>
 * This builder provides a fluent API for creating instances of
 * org.javahelpers.simple.builders.example.scoping.ScopedOwnerDto with method chaining and validation. Use the static
 * {@code create()} method to obtain a new builder instance, configure the desired properties using the setter methods,
 * and then call {@code build()} to create the final DTO.
 * 
 * <h4>Example:</h4>
 * 
 * <pre>{@code
 * ScopedOwnerDto result = ScopedOwnerDtoBuilder.create()
 *     .library(new LibraryHelperDto())
 *     .library(LibraryHelperDto::new)
 *     .sponsor(new SponsorDto())
 *     .sponsor(SponsorDto::new)
 *     .trusted(new TrustedHelperDto())
 *     .trusted(TrustedHelperDto::new)
 *     .trusted(trustedHelperDtoBuilder -> trustedHelperDtoBuilder)
 *     .build();
 * }</pre>
 */
@Generated("Generated by org.javahelpers.simple.builders.processor.BuilderProcessor")
@BuilderImplementation(forClass = ScopedOwnerDto.class)
public class ScopedOwnerDtoBuilder implements IBuilderBase<ScopedOwnerDto> {

  /**
   * Tracked value for <code>library</code>: library.
   */
  private TrackedValue<LibraryHelperDto> library = unsetValue();
  /**
   * Tracked value for <code>sponsor</code>: sponsor.
   */
  private TrackedValue<SponsorDto> sponsor = unsetValue();
  /**
   * Tracked value for <code>trusted</code>: trusted.
   */
  private TrackedValue<TrustedHelperDto> trusted = unsetValue();

  /**
   * Empty constructor of builder for {@code org.javahelpers.simple.builders.example.scoping.ScopedOwnerDto}.
   */
  public ScopedOwnerDtoBuilder() {
  }

  /**
   * Initialisation of builder for {@code org.javahelpers.simple.builders.example.scoping.ScopedOwnerDto} by a instance.
   * 
   * @param instance object instance for initialisiation
   */
  public ScopedOwnerDtoBuilder(ScopedOwnerDto instance) {
    this.library = initialValue(instance.getLibrary());
    this.sponsor = initialValue(instance.getSponsor());
    this.trusted = initialValue(instance.getTrusted());
  }

  /**
   * Creating a new builder for {@code org.javahelpers.simple.builders.example.scoping.ScopedOwnerDto}.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * ScopedOwnerDtoBuilder builder = ScopedOwnerDtoBuilder.create();
   * }</pre>
   * 
   * @return builder for {@code org.javahelpers.simple.builders.example.scoping.ScopedOwnerDto}
   */
  public static ScopedOwnerDtoBuilder create() {
    return new ScopedOwnerDtoBuilder();
  }

  /**
   * Sets the value for <code>library</code>.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setLibrary(LibraryHelperDto) setLibrary(LibraryHelperDto library)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.library(new LibraryHelperDto());
   * }</pre>
   * 
   * @param library library
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder library(LibraryHelperDto library) {
    this.library = changedValue(library);
    return this;
  }

  /**
   * Sets the value for <code>library</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setLibrary(LibraryHelperDto) setLibrary(LibraryHelperDto library)}
   * 
   * @param libraryConsumer consumer providing an instance of library
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder library(Consumer<LibraryHelperDto> libraryConsumer) {
    LibraryHelperDto consumer = this.library.isSet() ? this.library.value() : new LibraryHelperDto();
    libraryConsumer.accept(consumer);
    this.library = changedValue(consumer);
    return this;
  }

  /**
   * Sets the value for <code>library</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setLibrary(LibraryHelperDto) setLibrary(LibraryHelperDto library)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.library(LibraryHelperDto::new);
   * }</pre>
   * 
   * @param librarySupplier supplier for library
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder library(Supplier<LibraryHelperDto> librarySupplier) {
    this.library = changedValue(librarySupplier.get());
    return this;
  }

  /**
   * Sets the value for <code>sponsor</code>.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setSponsor(SponsorDto) setSponsor(SponsorDto sponsor)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.sponsor(new SponsorDto());
   * }</pre>
   * 
   * @param sponsor sponsor
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder sponsor(SponsorDto sponsor) {
    this.sponsor = changedValue(sponsor);
    return this;
  }

  /**
   * Sets the value for <code>sponsor</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setSponsor(SponsorDto) setSponsor(SponsorDto sponsor)}
   * 
   * @param sponsorConsumer consumer providing an instance of sponsor
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder sponsor(Consumer<SponsorDto> sponsorConsumer) {
    SponsorDto consumer = this.sponsor.isSet() ? this.sponsor.value() : new SponsorDto();
    sponsorConsumer.accept(consumer);
    this.sponsor = changedValue(consumer);
    return this;
  }

  /**
   * Sets the value for <code>sponsor</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setSponsor(SponsorDto) setSponsor(SponsorDto sponsor)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.sponsor(SponsorDto::new);
   * }</pre>
   * 
   * @param sponsorSupplier supplier for sponsor
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder sponsor(Supplier<SponsorDto> sponsorSupplier) {
    this.sponsor = changedValue(sponsorSupplier.get());
    return this;
  }

  /**
   * Sets the value for <code>trusted</code>.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setTrusted(TrustedHelperDto) setTrusted(TrustedHelperDto trusted)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.trusted(new TrustedHelperDto());
   * }</pre>
   * 
   * @param trusted trusted
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder trusted(TrustedHelperDto trusted) {
    this.trusted = changedValue(trusted);
    return this;
  }

  /**
   * Sets the value for <code>trusted</code> using a builder consumer that produces the value.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setTrusted(TrustedHelperDto) setTrusted(TrustedHelperDto trusted)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.trusted(trustedHelperDtoBuilder -> trustedHelperDtoBuilder);
   * }</pre>
   * 
   * @param trustedBuilderConsumer consumer providing an instance of a builder for trusted
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder trusted(Consumer<TrustedHelperDtoBuilder> trustedBuilderConsumer) {
    TrustedHelperDtoBuilder builder = this.trusted.isSet()
        ? new TrustedHelperDtoBuilder(this.trusted.value())
        : new TrustedHelperDtoBuilder();
    trustedBuilderConsumer.accept(builder);
    this.trusted = changedValue(builder.build());
    return this;
  }

  /**
   * Sets the value for <code>trusted</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link ScopedOwnerDto#setTrusted(TrustedHelperDto) setTrusted(TrustedHelperDto trusted)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.trusted(TrustedHelperDto::new);
   * }</pre>
   * 
   * @param trustedSupplier supplier for trusted
   * @return current instance of builder
   */
  public ScopedOwnerDtoBuilder trusted(Supplier<TrustedHelperDto> trustedSupplier) {
    this.trusted = changedValue(trustedSupplier.get());
    return this;
  }

  /**
   * Conditionally applies builder modifications if the condition is true.
   * 
   * @param condition the condition to evaluate
   * @param yesCondition the consumer to apply if condition is true
   * @return this builder instance
   */
  public ScopedOwnerDtoBuilder conditional(BooleanSupplier condition, Consumer<ScopedOwnerDtoBuilder> yesCondition) {
    return conditional(condition, yesCondition, null);
  }

  /**
   * Conditionally applies builder modifications based on a condition evaluation.
   * 
   * @param condition the condition to evaluate
   * @param trueCase the consumer to apply if condition is true
   * @param falseCase the consumer to apply if condition is false (can be null)
   * @return this builder instance
   */
  public ScopedOwnerDtoBuilder conditional(BooleanSupplier condition, Consumer<ScopedOwnerDtoBuilder> trueCase,
      Consumer<ScopedOwnerDtoBuilder> falseCase) {
    if (condition.getAsBoolean()) {
      trueCase.accept(this);
    } else if (falseCase != null) {
      falseCase.accept(this);
    }
    return this;
  }

  /**
   * Builds the configured DTO instance.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * ScopedOwnerDto result = builder.build();
   * }</pre>
   */
  @Override
  public ScopedOwnerDto build() {
    ScopedOwnerDto result = new ScopedOwnerDto();
    this.library.ifSet(result::setLibrary);
    this.sponsor.ifSet(result::setSponsor);
    this.trusted.ifSet(result::setTrusted);
    return result;
  }

  /**
   * Returns a string representation of this builder, including only fields that have been set.
   * 
   * @return string representation of the builder
   */
  @Override
  public String toString() {
    return new ToStringBuilder(this, BuilderToStringStyle.INSTANCE).append("library", this.library)
        .append("sponsor", this.sponsor)
        .append("trusted", this.trusted)
        .toString();
  }

  /**
   * Interface that can be implemented by the DTO to provide fluent modification methods.
   */
  public interface With {
    /**
     * Initializes a builder from an instance of this class, using methods of this builder to change values and returns
     * the new built object.
     * 
     * @param b the consumer to apply modifications
     * @return the modified instance
     */
    default ScopedOwnerDto with(Consumer<ScopedOwnerDtoBuilder> b) {
      ScopedOwnerDtoBuilder builder;
      try {
        builder = new ScopedOwnerDtoBuilder(ScopedOwnerDto.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'ScopedOwnerDtoBuilder.With' should only be implemented by classes, which could be casted to 'ScopedOwnerDto'",
            ex);
      }
      b.accept(builder);
      return builder.build();
    }

    /**
     * Creates a builder initialized from this instance.
     * 
     * @return a builder initialized with this instance's values
     */
    default ScopedOwnerDtoBuilder with() {
      try {
        return new ScopedOwnerDtoBuilder(ScopedOwnerDto.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'ScopedOwnerDtoBuilder.With' should only be implemented by classes, which could be casted to 'ScopedOwnerDto'",
            ex);
      }
    }
  }
}