package org.javahelpers.simple.builders.example.scoping;

import static org.javahelpers.simple.builders.core.util.TrackedValue.changedValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.initialValue;
import static org.javahelpers.simple.builders.core.util.TrackedValue.unsetValue;
import java.util.function.BooleanSupplier;
import java.util.function.Consumer;
import java.util.function.Supplier;
import javax.annotation.processing.Generated;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.javahelpers.simple.builders.core.annotations.BuilderImplementation;
import org.javahelpers.simple.builders.core.interfaces.IBuilderBase;
import org.javahelpers.simple.builders.core.util.BuilderToStringStyle;
import org.javahelpers.simple.builders.core.util.TrackedValue;

/**
 * Builder for {@code org.javahelpers.simple.builders.example.scoping.TrustedHelperDto}.
 * <p>
 * This builder provides a fluent API for creating instances of
 * org.javahelpers.simple.builders.example.scoping.TrustedHelperDto with method chaining and validation. Use the static
 * {@code create()} method to obtain a new builder instance, configure the desired properties using the setter methods,
 * and then call {@code build()} to create the final DTO.
 * 
 * <h4>Example:</h4>
 * 
 * <pre>{@code
 * TrustedHelperDto result = TrustedHelperDtoBuilder.create()
 *     .name("example value")
 *     .name("Hello %s", "World")
 *     .name(() -> "example value")
 *     .name(sb -> sb.append("text"))
 *     .build();
 * }</pre>
 */
@Generated("Generated by org.javahelpers.simple.builders.processor.BuilderProcessor")
@BuilderImplementation(forClass = TrustedHelperDto.class)
public class TrustedHelperDtoBuilder implements IBuilderBase<TrustedHelperDto> {

  /**
   * Tracked value for <code>name</code>: name.
   */
  private TrackedValue<String> name = unsetValue();

  /**
   * Empty constructor of builder for {@code org.javahelpers.simple.builders.example.scoping.TrustedHelperDto}.
   */
  public TrustedHelperDtoBuilder() {
  }

  /**
   * Initialisation of builder for {@code org.javahelpers.simple.builders.example.scoping.TrustedHelperDto} by a
   * instance.
   * 
   * @param instance object instance for initialisiation
   */
  public TrustedHelperDtoBuilder(TrustedHelperDto instance) {
    this.name = initialValue(instance.getName());
  }

  /**
   * Creating a new builder for {@code org.javahelpers.simple.builders.example.scoping.TrustedHelperDto}.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * TrustedHelperDtoBuilder builder = TrustedHelperDtoBuilder.create();
   * }</pre>
   * 
   * @return builder for {@code org.javahelpers.simple.builders.example.scoping.TrustedHelperDto}
   */
  public static TrustedHelperDtoBuilder create() {
    return new TrustedHelperDtoBuilder();
  }

  /**
   * Sets the value for <code>name</code>.
   * <p>
   * Generated from setter {@link TrustedHelperDto#setName(String) setName(String name)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.name("example value");
   * }</pre>
   * 
   * @param name name
   * @return current instance of builder
   */
  public TrustedHelperDtoBuilder name(String name) {
    this.name = changedValue(name);
    return this;
  }

  /**
   * Sets the value for <code>name</code> by executing the provided consumer.
   * <p>
   * Generated from setter {@link TrustedHelperDto#setName(String) setName(String name)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.name(sb -> sb.append("text"));
   * }</pre>
   * 
   * @param nameStringBuilderConsumer consumer providing an instance of name
   * @return current instance of builder
   */
  public TrustedHelperDtoBuilder name(Consumer<StringBuilder> nameStringBuilderConsumer) {
    StringBuilder builder = new StringBuilder();
    nameStringBuilderConsumer.accept(builder);
    this.name = changedValue(builder.toString());
    return this;
  }

  /**
   * Sets the value for <code>name</code> by invoking the provided supplier.
   * <p>
   * Generated from setter {@link TrustedHelperDto#setName(String) setName(String name)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.name(() -> "example value");
   * }</pre>
   * 
   * @param nameSupplier supplier for name
   * @return current instance of builder
   */
  public TrustedHelperDtoBuilder name(Supplier<String> nameSupplier) {
    this.name = changedValue(nameSupplier.get());
    return this;
  }

  /**
   * Sets the String value for <code>name</code> by using String.format(format, args). See
   * {@link String#format(String, Object...)} for details.
   * <p>
   * Generated from setter {@link TrustedHelperDto#setName(String) setName(String name)}
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * builder.name("Hello %s", "World");
   * }</pre>
   * 
   * @param format A format string
   * @param args Arguments referenced by the format specifiers in the format string.
   * @return current instance of builder
   */
  public TrustedHelperDtoBuilder name(String format, Object... args) {
    this.name = changedValue(String.format(format, args));
    return this;
  }

  /**
   * Validates that the name field is not null or empty.
   * <p>
   * Generated from setter {@link TrustedHelperDto#setName(String) setName(String name)}
   * 
   * @return this builder instance for chaining
   * @throws IllegalArgumentException if name is null or empty
   */
  TrustedHelperDtoBuilder validateName() {
    if (!name.isSet() || name.value().trim().isEmpty()) {
      throw new IllegalArgumentException("Name cannot be null or empty");
    }
    return this;
  }

  /**
   * Conditionally applies builder modifications if the condition is true.
   * 
   * @param condition the condition to evaluate
   * @param yesCondition the consumer to apply if condition is true
   * @return this builder instance
   */
  public TrustedHelperDtoBuilder conditional(BooleanSupplier condition,
      Consumer<TrustedHelperDtoBuilder> yesCondition) {
    return conditional(condition, yesCondition, null);
  }

  /**
   * Conditionally applies builder modifications based on a condition evaluation.
   * 
   * @param condition the condition to evaluate
   * @param trueCase the consumer to apply if condition is true
   * @param falseCase the consumer to apply if condition is false (can be null)
   * @return this builder instance
   */
  public TrustedHelperDtoBuilder conditional(BooleanSupplier condition, Consumer<TrustedHelperDtoBuilder> trueCase,
      Consumer<TrustedHelperDtoBuilder> falseCase) {
    if (condition.getAsBoolean()) {
      trueCase.accept(this);
    } else if (falseCase != null) {
      falseCase.accept(this);
    }
    return this;
  }

  /**
   * Builds the configured DTO instance.
   * 
   * <h4>Example:</h4>
   * 
   * <pre>{@code
   * TrustedHelperDto result = builder.build();
   * }</pre>
   */
  @Override
  public TrustedHelperDto build() {
    TrustedHelperDto result = new TrustedHelperDto();
    this.name.ifSet(result::setName);
    return result;
  }

  /**
   * Returns a string representation of this builder, including only fields that have been set.
   * 
   * @return string representation of the builder
   */
  @Override
  public String toString() {
    return new ToStringBuilder(this, BuilderToStringStyle.INSTANCE).append("name", this.name).toString();
  }

  /**
   * Interface that can be implemented by the DTO to provide fluent modification methods.
   */
  public interface With {
    /**
     * Initializes a builder from an instance of this class, using methods of this builder to change values and returns
     * the new built object.
     * 
     * @param b the consumer to apply modifications
     * @return the modified instance
     */
    default TrustedHelperDto with(Consumer<TrustedHelperDtoBuilder> b) {
      TrustedHelperDtoBuilder builder;
      try {
        builder = new TrustedHelperDtoBuilder(TrustedHelperDto.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'TrustedHelperDtoBuilder.With' should only be implemented by classes, which could be casted to 'TrustedHelperDto'",
            ex);
      }
      b.accept(builder);
      return builder.build();
    }

    /**
     * Creates a builder initialized from this instance.
     * 
     * @return a builder initialized with this instance's values
     */
    default TrustedHelperDtoBuilder with() {
      try {
        return new TrustedHelperDtoBuilder(TrustedHelperDto.class.cast(this));
      } catch (ClassCastException ex) {
        throw new IllegalArgumentException(
            "The interface 'TrustedHelperDtoBuilder.With' should only be implemented by classes, which could be casted to 'TrustedHelperDto'",
            ex);
      }
    }
  }
}